import React, { createContext, useContext, useState, useEffect } from 'react'

export type SupportedLanguage =
  | 'en' // English
  | 'es' // Spanish
  | 'hi' // Hindi
  | 'fr' // French
  | 'de' // German
  | 'zh' // Chinese (Simplified)
  | 'ar' // Arabic
  | 'ja' // Japanese
  | 'pt' // Portuguese
  | 'ru' // Russian
  | 'it' // Italian
  | 'bn' // Bengali

export interface LanguageMeta {
  code: SupportedLanguage
  label: string
  nativeName: string
  flag: string
}

export const SUPPORTED_LANGUAGES: LanguageMeta[] = [
  { code: 'en', label: 'English', nativeName: 'English', flag: '🇺🇸' },
  { code: 'es', label: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'hi', label: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'fr', label: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'de', label: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
  { code: 'zh', label: 'Chinese', nativeName: '中文 (简体)', flag: '🇨🇳' },
  { code: 'ar', label: 'Arabic', nativeName: 'العربية', flag: '🇸🇦' },
  { code: 'ja', label: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
  { code: 'pt', label: 'Portuguese', nativeName: 'Português', flag: '🇧🇷' },
  { code: 'ru', label: 'Russian', nativeName: 'Русский', flag: '🇷🇺' },
  { code: 'it', label: 'Italian', nativeName: 'Italiano', flag: '🇮🇹' },
  { code: 'bn', label: 'Bengali', nativeName: 'বাংলা', flag: '🇧🇩' },
]

export interface LanguageContextType {
  language: SupportedLanguage
  setLanguage: (lang: SupportedLanguage) => void
  t: (key: string) => string
  languages: LanguageMeta[]
}

export const translations: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.dashboard': 'Dashboard',
    'nav.history': 'Scan History',
    'nav.compare': 'Compare Products',
    'nav.future': 'Future Tools',
    'nav.settings': 'Settings',
    'nav.help': 'Help & Sources',
    'nav.logout': 'Log out',
    'nav.profile': 'Profile',
    'nav.searchPlaceholder': 'Search past scans or ingredients…',

    'home.title': 'Analyze a product',
    'home.subtitle': 'Paste an ingredient list or add ingredients one at a time.',
    'home.tabPaste': 'Paste Text',
    'home.tabManual': 'Build Manually',
    'home.tabScan': 'Scan',
    'home.tip': 'Tip: paste the full ingredient list exactly as printed on the pack for the most accurate report.',
    'home.productNameLabel': 'Product name (optional)',
    'home.productNamePlaceholder': 'e.g. Chocolate Cake or Maggi',
    'home.analyzeBtn': 'Analyze Ingredients',
    'home.recentScans': 'Recent scans',
    'home.addIngredient': 'Add ingredient',

    'dashboard.rescan': 'Re-scan',
    'dashboard.compare': 'Compare',
    'dashboard.safetyScore': 'Safety Score',
    'dashboard.aiSummary': 'AI Health Summary',
    'dashboard.ingredientBreakdown': 'Ingredient Breakdown',
    'dashboard.riskAnalysis': 'Risk Analysis',
    'dashboard.countryRegulation': 'Country Regulation',
    'dashboard.saferAlternatives': 'Safer Alternatives',
    'dashboard.quickStats': 'Quick Stats',
    'dashboard.ingredientsCount': 'Ingredients',
    'dashboard.flaggedCount': 'Flagged',
    'dashboard.allergyWarning': 'Allergy Warning',

    'compare.title': 'Compare products',
    'compare.subtitle': 'Select two scanned products to see which is the safer choice.',
    'compare.productA': 'Product A',
    'compare.productB': 'Product B',
    'compare.chooseProduct': 'Choose a product',
    'compare.changeProduct': 'Change product',
    'compare.compareNow': 'Compare Now',
    'compare.betterChoice': 'Better Choice',
    'compare.recommendation': 'Recommendation',

    'profile.title': 'Profile & Settings',
    'profile.account': 'Account',
    'profile.fitness': 'Gym & Fitness',
    'profile.allergies': 'Food Allergies',
    'profile.appearance': 'Appearance',
    'profile.language': 'Language',
    'profile.notifications': 'Notifications',
    'profile.privacy': 'Privacy & Data',
    'profile.saveChanges': 'Save Changes',
    'profile.darkMode': 'Dark mode',
    'profile.selectLanguage': 'Select your preferred language',
    'profile.logoutConfirm': 'Are you sure you want to log out?',
    'profile.loggedOutMsg': 'You have been logged out successfully.',

    'common.cancel': 'Cancel',
    'common.retry': 'Retry',
    'common.goHome': 'Go to Home',
    'common.contactSupport': 'Contact support',
    'common.compare': 'Compare',
    'common.delete': 'Delete',
    'common.changeProduct': 'Change product',
    'common.chooseProduct': 'Choose a product',
    'common.backToSetup': 'Back to Comparison Setup',
    'common.safetyPoints': 'safety points',

    'dashboard.scanned': 'Scanned',
    'dashboard.moreOptions': 'More options',
    'dashboard.needSecondOpinion': 'Need a second opinion?',
    'dashboard.viewHistory': 'View your scan history',

    'history.title': 'Scan History',
    'history.subtitleOne': 'saved scan — stored persistently.',
    'history.subtitleMany': 'saved scans — stored persistently.',
    'history.searchPlaceholder': 'Search scans…',
    'history.searchLabel': 'Search scan history',
    'history.clearAll': 'Clear all history',
    'history.clearConfirm': 'Are you sure you want to clear your entire scan history?',
    'history.clearedToast': 'Scan history cleared.',
    'history.removedPrefix': 'Removed',
    'history.removedSuffix': 'from scan history.',
    'history.emptyTitle': 'No scans yet',
    'history.emptyDesc': 'Analyze a product to start building your persistent scan history.',
    'history.emptyAction': 'Analyze Now',
    'history.noMatchStart': 'No scans match',
    'history.noMatchEnd': 'Try clearing your search.',
    'history.gridView': 'Grid view',
    'history.listView': 'List view',
    'history.compareTitle': 'Compare product',
    'history.deleteTitle': 'Delete scan',

    'compare.emptyTitle': 'Pick two products to compare',
    'compare.emptyDesc': 'Choose from your scan history or analyze a new product to get started.',
    'compare.emptyAction': 'Go to Scan History',
    'compare.noOtherProducts': 'No other scanned products available.',
    'compare.resultTitle': 'Comparison Result',
    'compare.backToSetup': 'Back to Comparison Setup',
    'compare.safetyScore': 'Safety Score',
    'compare.riskLevel': 'Risk Level',
    'compare.ingredientCount': 'Ingredient Count',
    'compare.harmfulCount': 'Harmful Ingredients',
    'compare.customFallback': 'Custom / Scanned',
    'compare.saferChoiceIs': 'is the safer choice — it scores',
    'compare.pointsHigherSuffix': 'points higher with fewer flagged ingredients.',

    'future.ocrTitle': 'OCR Scanner',
    'future.ocrDesc': "Coming soon — scan a label with your camera and we'll read the ingredients for you.",
    'future.barcodeTitle': 'Barcode Scanner',
    'future.barcodeDesc': 'Coming soon — scan a barcode to instantly pull up a full ingredient analysis.',
    'future.voiceTitle': 'Voice Assistant',
    'future.voiceDesc': 'Coming soon — ask NutriGuard AI questions about any ingredient out loud.',
    'future.langTitle': 'Multi-language Support',
    'future.langDesc': 'Coming soon — read your health reports in your preferred language.',
    'future.notifyMe': 'Notify Me',
    'future.notified': "We'll notify you",

    'ingredient.breadcrumbHome': 'Dashboard',
    'ingredient.backToDashboard': 'Back to Dashboard',
    'ingredient.description': 'Description',
    'ingredient.purpose': 'Purpose in Food',
    'ingredient.healthEffects': 'Health Effects',
    'ingredient.countryRegulations': 'Country Regulations',
    'ingredient.saferAlternatives': 'Safer Alternatives',
    'ingredient.researchSources': 'Research Sources',

    'analyzing.prefix': 'Analyzing',
    'analyzing.stage1': 'Parsing ingredients',
    'analyzing.stage2': 'Cross-referencing global regulations',
    'analyzing.stage3': 'Generating your health report',
    'analyzing.cancel': 'Cancel',

    'table.ingredient': 'Ingredient',
    'table.reason': 'Reason',
    'table.risk': 'Risk',
    'table.caption': 'Ingredient risk breakdown',

    'chart.safe': 'Safe',
    'chart.moderate': 'Moderate',
    'chart.highRisk': 'High Risk',
    'chart.unknown': 'Unknown',
    'chart.aria': 'Risk distribution chart',

    'badge.safe': 'Safe',
    'badge.moderate': 'Moderate Risk',
    'badge.high': 'High Risk',
    'badge.unknown': 'Unknown',

    'error.notFoundTitle': 'Page not found',
    'error.notFoundDesc': "The page you're looking for doesn't exist or may have moved.",
    'error.serverTitle': 'Something went wrong on our end',
    'error.serverDesc': 'Our team has been notified. Please try again in a moment.',
    'error.networkTitle': 'Check your internet connection',
    'error.networkDesc': "We couldn't reach NutriGuard AI. Reconnect and try again.",
    'error.noAnalysisTitle': "We couldn't find this scan",
    'error.noAnalysisDesc': 'This analysis may have been deleted or the link is incorrect.',
    'error.noAnalysisAction': 'Start a new analysis',
  },

  es: {
    'nav.home': 'Inicio',
    'nav.dashboard': 'Panel',
    'nav.history': 'Historial de Escaneos',
    'nav.compare': 'Comparar Productos',
    'nav.future': 'Próximas Herramientas',
    'nav.settings': 'Configuración',
    'nav.help': 'Ayuda y Fuentes',
    'nav.logout': 'Cerrar sesión',
    'nav.profile': 'Perfil',
    'nav.searchPlaceholder': 'Buscar escaneos o ingredientes…',

    'home.title': 'Analizar un producto',
    'home.subtitle': 'Pega una lista de ingredientes o añádelos uno a uno.',
    'home.tabPaste': 'Pegar Texto',
    'home.tabManual': 'Crear Manualmente',
    'home.tabScan': 'Escanear',
    'home.tip': 'Consejo: pega la lista completa exactamente como en el envase para mayor precisión.',
    'home.productNameLabel': 'Nombre del producto (opcional)',
    'home.productNamePlaceholder': 'p. ej. Pastel de Chocolate',
    'home.analyzeBtn': 'Analizar Ingredientes',
    'home.recentScans': 'Escaneos recientes',
    'home.addIngredient': 'Añadir ingrediente',

    'dashboard.rescan': 'Volver a escanear',
    'dashboard.compare': 'Comparar',
    'dashboard.safetyScore': 'Puntuación de Seguridad',
    'dashboard.aiSummary': 'Resumen de Salud IA',
    'dashboard.ingredientBreakdown': 'Desglose de Ingredientes',
    'dashboard.riskAnalysis': 'Análisis de Riesgo',
    'dashboard.countryRegulation': 'Regulación por País',
    'dashboard.saferAlternatives': 'Alternativas Más Seguras',
    'dashboard.quickStats': 'Estadísticas Rápidas',
    'dashboard.ingredientsCount': 'Ingredientes',
    'dashboard.flaggedCount': 'Marcados',
    'dashboard.allergyWarning': 'Aviso de Alergias',

    'compare.title': 'Comparar productos',
    'compare.subtitle': 'Selecciona dos productos para ver cuál es la opción más segura.',
    'compare.productA': 'Producto A',
    'compare.productB': 'Producto B',
    'compare.chooseProduct': 'Elige un producto',
    'compare.changeProduct': 'Cambiar producto',
    'compare.compareNow': 'Comparar Ahora',
    'compare.betterChoice': 'Mejor Opción',
    'compare.recommendation': 'Recomendación',

    'profile.title': 'Perfil y Configuración',
    'profile.account': 'Cuenta',
    'profile.fitness': 'Gimnasio y Fitness',
    'profile.allergies': 'Alergias Alimentarias',
    'profile.appearance': 'Apariencia',
    'profile.language': 'Idioma',
    'profile.notifications': 'Notificaciones',
    'profile.privacy': 'Privacidad y Datos',
    'profile.saveChanges': 'Guardar Cambios',
    'profile.darkMode': 'Modo oscuro',
    'profile.selectLanguage': 'Selecciona tu idioma preferido',
    'profile.logoutConfirm': '¿Estás seguro de que deseas cerrar sesión?',
    'profile.loggedOutMsg': 'Has cerrado sesión exitosamente.',

    'common.cancel': 'Cancelar',
    'common.retry': 'Reintentar',
    'common.goHome': 'Ir al inicio',
    'common.contactSupport': 'Contactar soporte',
    'common.compare': 'Comparar',
    'common.delete': 'Eliminar',
    'common.changeProduct': 'Cambiar producto',
    'common.chooseProduct': 'Elige un producto',
    'common.backToSetup': 'Volver a la comparación',
    'common.safetyPoints': 'puntos de seguridad',

    'dashboard.scanned': 'Analizado',
    'dashboard.moreOptions': 'Más opciones',
    'dashboard.needSecondOpinion': '¿Necesitas una segunda opinión?',
    'dashboard.viewHistory': 'Ver tu historial de escaneos',

    'history.title': 'Historial de Escaneos',
    'history.subtitleOne': 'escaneo guardado — almacenado de forma persistente.',
    'history.subtitleMany': 'escaneos guardados — almacenados de forma persistente.',
    'history.searchPlaceholder': 'Buscar escaneos…',
    'history.searchLabel': 'Buscar en el historial',
    'history.clearAll': 'Borrar todo el historial',
    'history.clearConfirm': '¿Seguro que quieres borrar todo tu historial de escaneos?',
    'history.clearedToast': 'Historial de escaneos borrado.',
    'history.removedPrefix': 'Eliminado',
    'history.removedSuffix': 'del historial de escaneos.',
    'history.emptyTitle': 'Aún no hay escaneos',
    'history.emptyDesc': 'Analiza un producto para empezar a crear tu historial.',
    'history.emptyAction': 'Analizar ahora',
    'history.noMatchStart': 'Ningún escaneo coincide con',
    'history.noMatchEnd': 'Prueba a borrar tu búsqueda.',
    'history.gridView': 'Vista de cuadrícula',
    'history.listView': 'Vista de lista',
    'history.compareTitle': 'Comparar producto',
    'history.deleteTitle': 'Eliminar escaneo',

    'compare.emptyTitle': 'Elige dos productos para comparar',
    'compare.emptyDesc': 'Elige de tu historial o analiza un producto nuevo para empezar.',
    'compare.emptyAction': 'Ir al historial de escaneos',
    'compare.noOtherProducts': 'No hay otros productos escaneados disponibles.',
    'compare.resultTitle': 'Resultado de la comparación',
    'compare.backToSetup': 'Volver a la comparación',
    'compare.safetyScore': 'Puntuación de seguridad',
    'compare.riskLevel': 'Nivel de riesgo',
    'compare.ingredientCount': 'Cantidad de ingredientes',
    'compare.harmfulCount': 'Ingredientes dañinos',
    'compare.customFallback': 'Personalizado / Escaneado',
    'compare.saferChoiceIs': 'es la opción más segura — obtiene',
    'compare.pointsHigherSuffix': 'puntos más con menos ingredientes marcados.',

    'future.ocrTitle': 'Escáner OCR',
    'future.ocrDesc': 'Próximamente — escanea una etiqueta con tu cámara y leeremos los ingredientes por ti.',
    'future.barcodeTitle': 'Escáner de código de barras',
    'future.barcodeDesc': 'Próximamente — escanea un código de barras para ver el análisis completo.',
    'future.voiceTitle': 'Asistente de voz',
    'future.voiceDesc': 'Próximamente — pregunta a NutriGuard AI sobre cualquier ingrediente en voz alta.',
    'future.langTitle': 'Soporte multilingüe',
    'future.langDesc': 'Próximamente — lee tus informes de salud en tu idioma preferido.',
    'future.notifyMe': 'Avísame',
    'future.notified': 'Te avisaremos',

    'ingredient.breadcrumbHome': 'Panel',
    'ingredient.backToDashboard': 'Volver al panel',
    'ingredient.description': 'Descripción',
    'ingredient.purpose': 'Función en el alimento',
    'ingredient.healthEffects': 'Efectos en la salud',
    'ingredient.countryRegulations': 'Regulación por país',
    'ingredient.saferAlternatives': 'Alternativas más seguras',
    'ingredient.researchSources': 'Fuentes de investigación',

    'analyzing.prefix': 'Analizando',
    'analyzing.stage1': 'Procesando ingredientes',
    'analyzing.stage2': 'Consultando regulaciones globales',
    'analyzing.stage3': 'Generando tu informe de salud',
    'analyzing.cancel': 'Cancelar',

    'table.ingredient': 'Ingrediente',
    'table.reason': 'Motivo',
    'table.risk': 'Riesgo',
    'table.caption': 'Desglose de riesgo por ingrediente',

    'chart.safe': 'Seguro',
    'chart.moderate': 'Moderado',
    'chart.highRisk': 'Riesgo alto',
    'chart.unknown': 'Desconocido',
    'chart.aria': 'Gráfico de distribución de riesgo',

    'badge.safe': 'Seguro',
    'badge.moderate': 'Riesgo moderado',
    'badge.high': 'Riesgo alto',
    'badge.unknown': 'Desconocido',

    'error.notFoundTitle': 'Página no encontrada',
    'error.notFoundDesc': 'La página que buscas no existe o pudo haberse movido.',
    'error.serverTitle': 'Algo salió mal de nuestro lado',
    'error.serverDesc': 'Nuestro equipo ha sido notificado. Inténtalo de nuevo en un momento.',
    'error.networkTitle': 'Revisa tu conexión a internet',
    'error.networkDesc': 'No pudimos conectar con NutriGuard AI. Reconéctate e inténtalo de nuevo.',
    'error.noAnalysisTitle': 'No pudimos encontrar este escaneo',
    'error.noAnalysisDesc': 'Este análisis pudo haberse eliminado o el enlace es incorrecto.',
    'error.noAnalysisAction': 'Iniciar un nuevo análisis',
  },

  hi: {
    'nav.home': 'होम',
    'nav.dashboard': 'डैशबोर्ड',
    'nav.history': 'स्कैन इतिहास',
    'nav.compare': 'उत्पादों की तुलना',
    'nav.future': 'भविष्य के टूल्स',
    'nav.settings': 'सेटिंग्स',
    'nav.help': 'सहायता और स्रोत',
    'nav.logout': 'लॉग आउट',
    'nav.profile': 'प्रोफ़ाइल',
    'nav.searchPlaceholder': 'सामग्री या पिछले स्कैन खोजें…',

    'home.title': 'उत्पाद का विश्लेषण करें',
    'home.subtitle': 'सामग्री सूची पेस्ट करें या एक-एक करके जोड़ें।',
    'home.tabPaste': 'टेक्स्ट पेस्ट करें',
    'home.tabManual': 'मैन्युअल जोड़ें',
    'home.tabScan': 'स्कैन',
    'home.tip': 'सुझाव: सबसे सटीक रिपोर्ट के लिए पैकेट पर मुद्रित पूरी सामग्री सूची दर्ज करें।',
    'home.productNameLabel': 'उत्पाद का नाम (वैकल्पिक)',
    'home.productNamePlaceholder': 'जैसे चॉकलेट केक या मैगी',
    'home.analyzeBtn': 'सामग्री का विश्लेषण करें',
    'home.recentScans': 'हालिया स्कैन',
    'home.addIngredient': 'सामग्री जोड़ें',

    'dashboard.rescan': 'पुनः स्कैन करें',
    'dashboard.compare': 'तुलना करें',
    'dashboard.safetyScore': 'सुरक्षा स्कोर',
    'dashboard.aiSummary': 'एआई स्वास्थ्य सारांश',
    'dashboard.ingredientBreakdown': 'सामग्री का विवरण',
    'dashboard.riskAnalysis': 'जोखिम विश्लेषण',
    'dashboard.countryRegulation': 'देश अनुसार नियम',
    'dashboard.saferAlternatives': 'सुरक्षित विकल्प',
    'dashboard.quickStats': 'त्वरित आंकड़े',
    'dashboard.ingredientsCount': 'कुल सामग्री',
    'dashboard.flaggedCount': 'चिह्नित हानिकारक',
    'dashboard.allergyWarning': 'एलर्जी चेतावनी',

    'compare.title': 'उत्पादों की तुलना करें',
    'compare.subtitle': 'देखें कि कौन सा उत्पाद स्वास्थ्य के लिए अधिक सुरक्षित है।',
    'compare.productA': 'उत्पाद A',
    'compare.productB': 'उत्पाद B',
    'compare.chooseProduct': 'उत्पाद चुनें',
    'compare.changeProduct': 'उत्पाद बदलें',
    'compare.compareNow': 'अभी तुलना करें',
    'compare.betterChoice': 'बेहतर विकल्प',
    'compare.recommendation': 'सिफारिश',

    'profile.title': 'प्रोफ़ाइल और सेटिंग्स',
    'profile.account': 'खाता',
    'profile.fitness': 'जिम और फिटनेस',
    'profile.allergies': 'खाद्य एलर्जी',
    'profile.appearance': 'दिखावट',
    'profile.language': 'भाषा',
    'profile.notifications': 'सूचनाएं',
    'profile.privacy': 'गोपनीयता और डेटा',
    'profile.saveChanges': 'परिवर्तन सहेजें',
    'profile.darkMode': 'डार्क मोड',
    'profile.selectLanguage': 'अपनी पसंदीदा भाषा चुनें',
    'profile.logoutConfirm': 'क्या आप वाकई लॉग आउट करना चाहते हैं?',
    'profile.loggedOutMsg': 'आप सफलतापूर्वक लॉग आउट हो गए हैं।',

    'common.cancel': 'रद्द करें',
    'common.retry': 'पुनः प्रयास करें',
    'common.goHome': 'होम पर जाएं',
    'common.contactSupport': 'सहायता से संपर्क करें',
    'common.compare': 'तुलना करें',
    'common.delete': 'हटाएं',
    'common.changeProduct': 'उत्पाद बदलें',
    'common.chooseProduct': 'उत्पाद चुनें',
    'common.backToSetup': 'तुलना सेटअप पर वापस जाएं',
    'common.safetyPoints': 'सुरक्षा अंक',

    'dashboard.scanned': 'स्कैन किया गया',
    'dashboard.moreOptions': 'अधिक विकल्प',
    'dashboard.needSecondOpinion': 'दूसरी राय चाहिए?',
    'dashboard.viewHistory': 'अपना स्कैन इतिहास देखें',

    'history.title': 'स्कैन इतिहास (History)',
    'history.subtitleOne': 'सहेजा गया स्कैन — स्थायी रूप से संग्रहीत।',
    'history.subtitleMany': 'सहेजे गए स्कैन — स्थायी रूप से संग्रहीत।',
    'history.searchPlaceholder': 'स्कैन खोजें…',
    'history.searchLabel': 'स्कैन इतिहास खोजें',
    'history.clearAll': 'पूरा इतिहास साफ़ करें',
    'history.clearConfirm': 'क्या आप वाकई पूरा स्कैन इतिहास साफ़ करना चाहते हैं?',
    'history.clearedToast': 'स्कैन इतिहास साफ़ कर दिया गया।',
    'history.removedPrefix': 'हटाया गया',
    'history.removedSuffix': 'स्कैन इतिहास से।',
    'history.emptyTitle': 'अभी कोई स्कैन नहीं',
    'history.emptyDesc': 'अपना स्थायी स्कैन इतिहास बनाने के लिए उत्पाद का विश्लेषण करें।',
    'history.emptyAction': 'अभी विश्लेषण करें',
    'history.noMatchStart': 'कोई स्कैन मेल नहीं खाता',
    'history.noMatchEnd': 'अपनी खोज साफ़ करके देखें।',
    'history.gridView': 'ग्रिड दृश्य',
    'history.listView': 'सूची दृश्य',
    'history.compareTitle': 'उत्पाद की तुलना करें',
    'history.deleteTitle': 'स्कैन हटाएं',

    'compare.emptyTitle': 'तुलना के लिए दो उत्पाद चुनें',
    'compare.emptyDesc': 'अपने स्कैन इतिहास से चुनें या नया उत्पाद विश्लेषित करें।',
    'compare.emptyAction': 'स्कैन इतिहास पर जाएं',
    'compare.noOtherProducts': 'कोई अन्य स्कैन किए गए उत्पाद उपलब्ध नहीं हैं।',
    'compare.resultTitle': 'तुलना परिणाम',
    'compare.backToSetup': 'तुलना सेटअप पर वापस जाएं',
    'compare.safetyScore': 'सुरक्षा स्कोर (Safety Score)',
    'compare.riskLevel': 'जोखिम स्तर',
    'compare.ingredientCount': 'सामग्री की संख्या',
    'compare.harmfulCount': 'हानिकारक सामग्री',
    'compare.customFallback': 'कस्टम / स्कैन किया गया',
    'compare.saferChoiceIs': 'अधिक सुरक्षित विकल्प है — इसे मिले',
    'compare.pointsHigherSuffix': 'अंक अधिक, कम चिह्नित सामग्री के साथ।',

    'future.ocrTitle': 'OCR स्कैनर',
    'future.ocrDesc': 'जल्द आ रहा है — अपने कैमरे से लेबल स्कैन करें, हम सामग्री पढ़ लेंगे।',
    'future.barcodeTitle': 'बारकोड स्कैनर',
    'future.barcodeDesc': 'जल्द आ रहा है — पूर्ण विश्लेषण के लिए बारकोड स्कैन करें।',
    'future.voiceTitle': 'वॉयस असिस्टेंट',
    'future.voiceDesc': 'जल्द आ रहा है — किसी भी सामग्री के बारे में बोलकर पूछें।',
    'future.langTitle': 'बहुभाषी समर्थन',
    'future.langDesc': 'जल्द आ रहा है — अपनी पसंदीदा भाषा में स्वास्थ्य रिपोर्ट पढ़ें।',
    'future.notifyMe': 'मुझे सूचित करें',
    'future.notified': 'हम आपको सूचित करेंगे',

    'ingredient.breadcrumbHome': 'डैशबोर्ड (Dashboard)',
    'ingredient.backToDashboard': 'डैशबोर्ड पर वापस जाएं',
    'ingredient.description': 'विवरण',
    'ingredient.purpose': 'खाद्य में उद्देश्य',
    'ingredient.healthEffects': 'स्वास्थ्य प्रभाव',
    'ingredient.countryRegulations': 'देश अनुसार नियम',
    'ingredient.saferAlternatives': 'सुरक्षित विकल्प',
    'ingredient.researchSources': 'शोध स्रोत',

    'analyzing.prefix': 'विश्लेषण हो रहा है',
    'analyzing.stage1': 'सामग्री को संसाधित किया जा रहा है',
    'analyzing.stage2': 'वैश्विक नियमों से मिलान हो रहा है',
    'analyzing.stage3': 'आपकी स्वास्थ्य रिपोर्ट बनाई जा रही है',
    'analyzing.cancel': 'रद्द करें',

    'table.ingredient': 'सामग्री',
    'table.reason': 'कारण',
    'table.risk': 'जोखिम',
    'table.caption': 'सामग्री जोखिम विवरण',

    'chart.safe': 'सुरक्षित',
    'chart.moderate': 'मध्यम',
    'chart.highRisk': 'उच्च जोखिम',
    'chart.unknown': 'अज्ञात',
    'chart.aria': 'जोखिम वितरण चार्ट',

    'badge.safe': 'सुरक्षित',
    'badge.moderate': 'मध्यम जोखिम',
    'badge.high': 'उच्च जोखिम',
    'badge.unknown': 'अज्ञात',

    'error.notFoundTitle': 'पेज नहीं मिला',
    'error.notFoundDesc': 'आप जो पेज खोज रहे हैं वह मौजूद नहीं है या स्थानांतरित हो गया है।',
    'error.serverTitle': 'हमारी ओर से कुछ गलत हुआ',
    'error.serverDesc': 'हमारी टीम को सूचित कर दिया गया है। कृपया कुछ देर में पुनः प्रयास करें।',
    'error.networkTitle': 'अपना इंटरनेट कनेक्शन जांचें',
    'error.networkDesc': 'हम NutriGuard AI से संपर्क नहीं कर सके। पुनः कनेक्ट करके प्रयास करें।',
    'error.noAnalysisTitle': 'यह स्कैन नहीं मिला',
    'error.noAnalysisDesc': 'यह विश्लेषण हटाया गया हो सकता है या लिंक गलत है।',
    'error.noAnalysisAction': 'नया विश्लेषण शुरू करें',
  },

  fr: {
    'nav.home': 'Accueil',
    'nav.dashboard': 'Tableau de bord',
    'nav.history': 'Historique des analyses',
    'nav.compare': 'Comparer des produits',
    'nav.future': 'Outils futurs',
    'nav.settings': 'Paramètres',
    'nav.help': 'Aide & Sources',
    'nav.logout': 'Se déconnecter',
    'nav.profile': 'Profil',
    'nav.searchPlaceholder': 'Rechercher des ingrédients ou analyses…',

    'home.title': 'Analyser un produit',
    'home.subtitle': 'Collez une liste d’ingrédients ou ajoutez-les un par un.',
    'home.tabPaste': 'Coller le texte',
    'home.tabManual': 'Créer manuellement',
    'home.tabScan': 'Scanner',
    'home.tip': 'Astuce : collez la liste complète imprimée sur l’emballage pour un rapport optimal.',
    'home.productNameLabel': 'Nom du produit (optionnel)',
    'home.productNamePlaceholder': 'ex. Gâteau au chocolat',
    'home.analyzeBtn': 'Analyser les ingrédients',
    'home.recentScans': 'Analyses récentes',
    'home.addIngredient': 'Ajouter un ingrédient',

    'dashboard.rescan': 'Réanalyser',
    'dashboard.compare': 'Comparer',
    'dashboard.safetyScore': 'Score de Sécurité',
    'dashboard.aiSummary': 'Résumé Santé IA',
    'dashboard.ingredientBreakdown': 'Détail des ingrédients',
    'dashboard.riskAnalysis': 'Analyse des risques',
    'dashboard.countryRegulation': 'Réglementation par pays',
    'dashboard.saferAlternatives': 'Alternatives plus saines',
    'dashboard.quickStats': 'Statistiques rapides',
    'dashboard.ingredientsCount': 'Ingrédients',
    'dashboard.flaggedCount': 'Signalés',
    'dashboard.allergyWarning': 'Alerte Allergènes',

    'compare.title': 'Comparer les produits',
    'compare.subtitle': 'Sélectionnez deux produits pour identifier le plus sain.',
    'compare.productA': 'Produit A',
    'compare.productB': 'Produit B',
    'compare.chooseProduct': 'Choisir un produit',
    'compare.changeProduct': 'Changer de produit',
    'compare.compareNow': 'Comparer maintenant',
    'compare.betterChoice': 'Meilleur choix',
    'compare.recommendation': 'Recommandation',

    'profile.title': 'Profil & Paramètres',
    'profile.account': 'Compte',
    'profile.fitness': 'Gym & Fitness',
    'profile.allergies': 'Allergies Alimentaires',
    'profile.appearance': 'Apparence',
    'profile.language': 'Langue',
    'profile.notifications': 'Notifications',
    'profile.privacy': 'Confidentialité & Données',
    'profile.saveChanges': 'Enregistrer les modifications',
    'profile.darkMode': 'Mode sombre',
    'profile.selectLanguage': 'Sélectionnez votre langue préférée',
    'profile.logoutConfirm': 'Êtes-vous sûr de vouloir vous déconnecter ?',
    'profile.loggedOutMsg': 'Vous avez été déconnecté avec succès.',

    'common.cancel': 'Annuler',
    'common.retry': 'Réessayer',
    'common.goHome': "Aller à l'accueil",
    'common.contactSupport': 'Contacter le support',
    'common.compare': 'Comparer',
    'common.delete': 'Supprimer',
    'common.changeProduct': 'Changer de produit',
    'common.chooseProduct': 'Choisir un produit',
    'common.backToSetup': 'Retour à la comparaison',
    'common.safetyPoints': 'points de sécurité',

    'dashboard.scanned': 'Analysé le',
    'dashboard.moreOptions': "Plus d'options",
    'dashboard.needSecondOpinion': 'Besoin d’un second avis ?',
    'dashboard.viewHistory': 'Voir votre historique des analyses',

    'history.title': 'Historique des analyses',
    'history.subtitleOne': 'analyse enregistrée — conservée de façon persistante.',
    'history.subtitleMany': 'analyses enregistrées — conservées de façon persistante.',
    'history.searchPlaceholder': 'Rechercher des analyses…',
    'history.searchLabel': "Rechercher dans l'historique",
    'history.clearAll': "Effacer tout l'historique",
    'history.clearConfirm': 'Voulez-vous vraiment effacer tout votre historique ?',
    'history.clearedToast': 'Historique effacé.',
    'history.removedPrefix': 'Supprimé',
    'history.removedSuffix': "de l'historique des analyses.",
    'history.emptyTitle': 'Aucune analyse pour le moment',
    'history.emptyDesc': 'Analysez un produit pour commencer votre historique.',
    'history.emptyAction': 'Analyser maintenant',
    'history.noMatchStart': 'Aucune analyse ne correspond à',
    'history.noMatchEnd': 'Essayez d’effacer votre recherche.',
    'history.gridView': 'Vue grille',
    'history.listView': 'Vue liste',
    'history.compareTitle': 'Comparer le produit',
    'history.deleteTitle': "Supprimer l'analyse",

    'compare.emptyTitle': 'Choisissez deux produits à comparer',
    'compare.emptyDesc': 'Choisissez depuis votre historique ou analysez un nouveau produit.',
    'compare.emptyAction': "Aller à l'historique",
    'compare.noOtherProducts': 'Aucun autre produit analysé disponible.',
    'compare.resultTitle': 'Résultat de la comparaison',
    'compare.backToSetup': 'Retour à la comparaison',
    'compare.safetyScore': 'Score de sécurité',
    'compare.riskLevel': 'Niveau de risque',
    'compare.ingredientCount': "Nombre d'ingrédients",
    'compare.harmfulCount': 'Ingrédients nocifs',
    'compare.customFallback': 'Personnalisé / Scanné',
    'compare.saferChoiceIs': 'est le choix le plus sûr — il obtient',
    'compare.pointsHigherSuffix': 'points de plus avec moins d’ingrédients signalés.',

    'future.ocrTitle': 'Scanner OCR',
    'future.ocrDesc': 'Bientôt — scannez une étiquette avec votre caméra, nous lirons les ingrédients.',
    'future.barcodeTitle': 'Scanner de code-barres',
    'future.barcodeDesc': 'Bientôt — scannez un code-barres pour obtenir l’analyse complète.',
    'future.voiceTitle': 'Assistant vocal',
    'future.voiceDesc': 'Bientôt — interrogez NutriGuard AI à voix haute sur tout ingrédient.',
    'future.langTitle': 'Support multilingue',
    'future.langDesc': 'Bientôt — lisez vos rapports santé dans votre langue préférée.',
    'future.notifyMe': 'Me notifier',
    'future.notified': 'Nous vous notifierons',

    'ingredient.breadcrumbHome': 'Tableau de bord',
    'ingredient.backToDashboard': 'Retour au tableau de bord',
    'ingredient.description': 'Description',
    'ingredient.purpose': 'Rôle dans l’aliment',
    'ingredient.healthEffects': 'Effets sur la santé',
    'ingredient.countryRegulations': 'Réglementation par pays',
    'ingredient.saferAlternatives': 'Alternatives plus saines',
    'ingredient.researchSources': 'Sources scientifiques',

    'analyzing.prefix': 'Analyse de',
    'analyzing.stage1': 'Lecture des ingrédients',
    'analyzing.stage2': 'Vérification des réglementations mondiales',
    'analyzing.stage3': 'Génération de votre rapport santé',
    'analyzing.cancel': 'Annuler',

    'table.ingredient': 'Ingrédient',
    'table.reason': 'Motif',
    'table.risk': 'Risque',
    'table.caption': 'Détail des risques par ingrédient',

    'chart.safe': 'Sûr',
    'chart.moderate': 'Modéré',
    'chart.highRisk': 'Risque élevé',
    'chart.unknown': 'Inconnu',
    'chart.aria': 'Graphique de répartition des risques',

    'badge.safe': 'Sûr',
    'badge.moderate': 'Risque modéré',
    'badge.high': 'Risque élevé',
    'badge.unknown': 'Inconnu',

    'error.notFoundTitle': 'Page introuvable',
    'error.notFoundDesc': 'La page recherchée n’existe pas ou a été déplacée.',
    'error.serverTitle': 'Un problème est survenu de notre côté',
    'error.serverDesc': 'Notre équipe a été notifiée. Veuillez réessayer dans un moment.',
    'error.networkTitle': 'Vérifiez votre connexion internet',
    'error.networkDesc': 'Nous n’avons pas pu joindre NutriGuard AI. Reconnectez-vous et réessayez.',
    'error.noAnalysisTitle': 'Analyse introuvable',
    'error.noAnalysisDesc': 'Cette analyse a peut-être été supprimée ou le lien est incorrect.',
    'error.noAnalysisAction': 'Démarrer une nouvelle analyse',
  },

  de: {
    'nav.home': 'Startseite',
    'nav.dashboard': 'Übersicht',
    'nav.history': 'Scan-Verlauf',
    'nav.compare': 'Produkte vergleichen',
    'nav.future': 'Zukünftige Tools',
    'nav.settings': 'Einstellungen',
    'nav.help': 'Hilfe & Quellen',
    'nav.logout': 'Abmelden',
    'nav.profile': 'Profil',
    'nav.searchPlaceholder': 'Zutaten oder Scans suchen…',

    'home.title': 'Produkt analysieren',
    'home.subtitle': 'Fügen Sie eine Zutatenliste ein oder tragen Sie Zutaten einzeln ein.',
    'home.tabPaste': 'Text einfügen',
    'home.tabManual': 'Manuell erstellen',
    'home.tabScan': 'Scannen',
    'home.tip': 'Tipp: Fügen Sie die vollständige Zutatenliste ein, um die genaueste Analyse zu erhalten.',
    'home.productNameLabel': 'Produktname (optional)',
    'home.productNamePlaceholder': 'z. B. Schokoladenkuchen',
    'home.analyzeBtn': 'Zutaten analysieren',
    'home.recentScans': 'Kürzliche Scans',
    'home.addIngredient': 'Zutat hinzufügen',

    'dashboard.rescan': 'Erneut scannen',
    'dashboard.compare': 'Vergleichen',
    'dashboard.safetyScore': 'Sicherheitsbewertung',
    'dashboard.aiSummary': 'KI-Gesundheitsübersicht',
    'dashboard.ingredientBreakdown': 'Zutatenübersicht',
    'dashboard.riskAnalysis': 'Risikoanalyse',
    'dashboard.countryRegulation': 'Länderbestimmungen',
    'dashboard.saferAlternatives': 'Sicherere Alternativen',
    'dashboard.quickStats': 'Schnellstatistik',
    'dashboard.ingredientsCount': 'Zutaten',
    'dashboard.flaggedCount': 'Bedenklich',
    'dashboard.allergyWarning': 'Allergiewarnung',

    'compare.title': 'Produkte vergleichen',
    'compare.subtitle': 'Wählen Sie zwei Produkte, um die gesündere Wahl zu finden.',
    'compare.productA': 'Produkt A',
    'compare.productB': 'Produkt B',
    'compare.chooseProduct': 'Produkt auswählen',
    'compare.changeProduct': 'Produkt ändern',
    'compare.compareNow': 'Jetzt vergleichen',
    'compare.betterChoice': 'Bessere Wahl',
    'compare.recommendation': 'Empfehlung',

    'profile.title': 'Profil & Einstellungen',
    'profile.account': 'Konto',
    'profile.fitness': 'Fitness & Gym',
    'profile.allergies': 'Lebensmittelallergien',
    'profile.appearance': 'Erscheinungsbild',
    'profile.language': 'Sprache',
    'profile.notifications': 'Benachrichtigungen',
    'profile.privacy': 'Datenschutz & Daten',
    'profile.saveChanges': 'Änderungen speichern',
    'profile.darkMode': 'Dunkelmodus',
    'profile.selectLanguage': 'Wählen Sie Ihre bevorzugte Sprache',
    'profile.logoutConfirm': 'Möchten Sie sich wirklich abmelden?',
    'profile.loggedOutMsg': 'Sie wurden erfolgreich abgemeldet.',

    'common.cancel': 'Abbrechen',
    'common.retry': 'Wiederholen',
    'common.goHome': 'Zur Startseite',
    'common.contactSupport': 'Support kontaktieren',
    'common.compare': 'Vergleichen',
    'common.delete': 'Löschen',
    'common.changeProduct': 'Produkt ändern',
    'common.chooseProduct': 'Produkt auswählen',
    'common.backToSetup': 'Zurück zum Vergleich',
    'common.safetyPoints': 'Sicherheitspunkte',

    'dashboard.scanned': 'Gescannt am',
    'dashboard.moreOptions': 'Weitere Optionen',
    'dashboard.needSecondOpinion': 'Eine zweite Meinung gefällig?',
    'dashboard.viewHistory': 'Deinen Scan-Verlauf ansehen',

    'history.title': 'Scan-Verlauf',
    'history.subtitleOne': 'gespeicherter Scan — dauerhaft gespeichert.',
    'history.subtitleMany': 'gespeicherte Scans — dauerhaft gespeichert.',
    'history.searchPlaceholder': 'Scans suchen…',
    'history.searchLabel': 'Scan-Verlauf durchsuchen',
    'history.clearAll': 'Gesamten Verlauf löschen',
    'history.clearConfirm': 'Möchtest du wirklich deinen gesamten Scan-Verlauf löschen?',
    'history.clearedToast': 'Scan-Verlauf gelöscht.',
    'history.removedPrefix': 'Entfernt',
    'history.removedSuffix': 'aus dem Scan-Verlauf.',
    'history.emptyTitle': 'Noch keine Scans',
    'history.emptyDesc': 'Analysiere ein Produkt, um deinen Verlauf aufzubauen.',
    'history.emptyAction': 'Jetzt analysieren',
    'history.noMatchStart': 'Keine Scans passen zu',
    'history.noMatchEnd': 'Versuche, deine Suche zu löschen.',
    'history.gridView': 'Rasteransicht',
    'history.listView': 'Listenansicht',
    'history.compareTitle': 'Produkt vergleichen',
    'history.deleteTitle': 'Scan löschen',

    'compare.emptyTitle': 'Wähle zwei Produkte zum Vergleich',
    'compare.emptyDesc': 'Wähle aus deinem Verlauf oder analysiere ein neues Produkt.',
    'compare.emptyAction': 'Zum Scan-Verlauf',
    'compare.noOtherProducts': 'Keine weiteren gescannten Produkte verfügbar.',
    'compare.resultTitle': 'Vergleichsergebnis',
    'compare.backToSetup': 'Zurück zum Vergleich',
    'compare.safetyScore': 'Sicherheitsbewertung',
    'compare.riskLevel': 'Risikostufe',
    'compare.ingredientCount': 'Zutatenanzahl',
    'compare.harmfulCount': 'Bedenkliche Zutaten',
    'compare.customFallback': 'Benutzerdefiniert / Gescannt',
    'compare.saferChoiceIs': 'ist die sicherere Wahl — mit',
    'compare.pointsHigherSuffix': 'Punkten mehr und weniger bedenklichen Zutaten.',

    'future.ocrTitle': 'OCR-Scanner',
    'future.ocrDesc': 'Bald — scanne ein Etikett mit deiner Kamera, wir lesen die Zutaten aus.',
    'future.barcodeTitle': 'Barcode-Scanner',
    'future.barcodeDesc': 'Bald — scanne einen Barcode für die komplette Analyse.',
    'future.voiceTitle': 'Sprachassistent',
    'future.voiceDesc': 'Bald — frage NutriGuard AI per Sprache zu jeder Zutat.',
    'future.langTitle': 'Mehrsprachigkeit',
    'future.langDesc': 'Bald — lies deine Gesundheitsberichte in deiner Sprache.',
    'future.notifyMe': 'Benachrichtige mich',
    'future.notified': 'Wir benachrichtigen dich',

    'ingredient.breadcrumbHome': 'Übersicht',
    'ingredient.backToDashboard': 'Zurück zur Übersicht',
    'ingredient.description': 'Beschreibung',
    'ingredient.purpose': 'Funktion im Lebensmittel',
    'ingredient.healthEffects': 'Gesundheitliche Wirkungen',
    'ingredient.countryRegulations': 'Länderbestimmungen',
    'ingredient.saferAlternatives': 'Sicherere Alternativen',
    'ingredient.researchSources': 'Forschungsquellen',

    'analyzing.prefix': 'Analysiere',
    'analyzing.stage1': 'Zutaten werden gelesen',
    'analyzing.stage2': 'Globale Bestimmungen werden geprüft',
    'analyzing.stage3': 'Gesundheitsbericht wird erstellt',
    'analyzing.cancel': 'Abbrechen',

    'table.ingredient': 'Zutat',
    'table.reason': 'Grund',
    'table.risk': 'Risiko',
    'table.caption': 'Risikoübersicht pro Zutat',

    'chart.safe': 'Sicher',
    'chart.moderate': 'Mittel',
    'chart.highRisk': 'Hohes Risiko',
    'chart.unknown': 'Unbekannt',
    'chart.aria': 'Risikoverteilungsdiagramm',

    'badge.safe': 'Sicher',
    'badge.moderate': 'Mittleres Risiko',
    'badge.high': 'Hohes Risiko',
    'badge.unknown': 'Unbekannt',

    'error.notFoundTitle': 'Seite nicht gefunden',
    'error.notFoundDesc': 'Die gesuchte Seite existiert nicht oder wurde verschoben.',
    'error.serverTitle': 'Auf unserer Seite ist etwas schiefgelaufen',
    'error.serverDesc': 'Unser Team wurde benachrichtigt. Bitte versuche es gleich erneut.',
    'error.networkTitle': 'Überprüfe deine Internetverbindung',
    'error.networkDesc': 'Wir konnten NutriGuard AI nicht erreichen. Verbinde dich erneut.',
    'error.noAnalysisTitle': 'Dieser Scan wurde nicht gefunden',
    'error.noAnalysisDesc': 'Diese Analyse wurde möglicherweise gelöscht oder der Link ist falsch.',
    'error.noAnalysisAction': 'Neue Analyse starten',
  },

  zh: {
    'nav.home': '首页',
    'nav.dashboard': '仪表板',
    'nav.history': '检测历史',
    'nav.compare': '对比产品',
    'nav.future': '未来功能',
    'nav.settings': '设置',
    'nav.help': '帮助与数据源',
    'nav.logout': '退出登录',
    'nav.profile': '个人资料',
    'nav.searchPlaceholder': '搜索过往检测或成分…',

    'home.title': '分析产品成分',
    'home.subtitle': '粘贴成分表或逐一手动添加配料。',
    'home.tabPaste': '粘贴文本',
    'home.tabManual': '手动输入',
    'home.tabScan': '拍照扫描',
    'home.tip': '提示：完整粘贴包装上的配料表可获得最准确的分析报告。',
    'home.productNameLabel': '产品名称（可选）'
    ,
    'home.productNamePlaceholder': '例如：巧克力蛋糕 或 方便面',
    'home.analyzeBtn': '开始分析成分',
    'home.recentScans': '近期检测',
    'home.addIngredient': '添加配料',

    'dashboard.rescan': '重新检测',
    'dashboard.compare': '对比',
    'dashboard.safetyScore': '安全评分',
    'dashboard.aiSummary': 'AI健康总结',
    'dashboard.ingredientBreakdown': '配料细分',
    'dashboard.riskAnalysis': '风险分析',
    'dashboard.countryRegulation': '各国监管情况',
    'dashboard.saferAlternatives': '更安全的替代品',
    'dashboard.quickStats': '关键数据',
    'dashboard.ingredientsCount': '总配料',
    'dashboard.flaggedCount': '关注成分',
    'dashboard.allergyWarning': '过敏原预警',

    'compare.title': '对比产品',
    'compare.subtitle': '选择两款已检测的产品，查看哪个更安全。',
    'compare.productA': '产品 A',
    'compare.productB': '产品 B',
    'compare.chooseProduct': '选择产品',
    'compare.changeProduct': '更换产品',
    'compare.compareNow': '立即对比',
    'compare.betterChoice': '更佳选择',
    'compare.recommendation': '健康建议',

    'profile.title': '个人设置',
    'profile.account': '账号',
    'profile.fitness': '健身与运动',
    'profile.allergies': '食物过敏',
    'profile.appearance': '外观',
    'profile.language': '语言',
    'profile.notifications': '通知',
    'profile.privacy': '隐私与数据',
    'profile.saveChanges': '保存修改',
    'profile.darkMode': '深色模式',
    'profile.selectLanguage': '选择首选语言',
    'profile.logoutConfirm': '确定要退出登录吗？',
    'profile.loggedOutMsg': '您已成功退出登录。',

    'common.cancel': '取消',
    'common.retry': '重试',
    'common.goHome': '返回首页',
    'common.contactSupport': '联系客服',
    'common.compare': '对比',
    'common.delete': '删除',
    'common.changeProduct': '更换产品',
    'common.chooseProduct': '选择产品',
    'common.backToSetup': '返回对比设置',
    'common.safetyPoints': '安全分',

    'dashboard.scanned': '检测于',
    'dashboard.moreOptions': '更多选项',
    'dashboard.needSecondOpinion': '需要第二意见？',
    'dashboard.viewHistory': '查看你的检测历史',

    'history.title': '检测历史',
    'history.subtitleOne': '条已保存检测 — 已持久存储。',
    'history.subtitleMany': '条已保存检测 — 已持久存储。',
    'history.searchPlaceholder': '搜索检测…',
    'history.searchLabel': '搜索检测历史',
    'history.clearAll': '清空全部历史',
    'history.clearConfirm': '确定要清空全部检测历史吗？',
    'history.clearedToast': '检测历史已清空。',
    'history.removedPrefix': '已删除',
    'history.removedSuffix': '，移出检测历史。',
    'history.emptyTitle': '暂无检测',
    'history.emptyDesc': '分析一款产品，开始建立你的持久检测历史。',
    'history.emptyAction': '立即分析',
    'history.noMatchStart': '没有匹配的检测',
    'history.noMatchEnd': '试试清空搜索条件。',
    'history.gridView': '网格视图',
    'history.listView': '列表视图',
    'history.compareTitle': '对比产品',
    'history.deleteTitle': '删除检测',

    'compare.emptyTitle': '选择两款产品进行对比',
    'compare.emptyDesc': '从检测历史中选择，或分析一款新产品开始。',
    'compare.emptyAction': '前往检测历史',
    'compare.noOtherProducts': '暂无其他已检测产品。',
    'compare.resultTitle': '对比结果',
    'compare.backToSetup': '返回对比设置',
    'compare.safetyScore': '安全评分',
    'compare.riskLevel': '风险等级',
    'compare.ingredientCount': '配料数量',
    'compare.harmfulCount': '有害配料',
    'compare.customFallback': '自定义 / 已检测',
    'compare.saferChoiceIs': '是更安全的选择 — 高出',
    'compare.pointsHigherSuffix': '分，且关注成分更少。',

    'future.ocrTitle': 'OCR 扫描仪',
    'future.ocrDesc': '即将上线 — 用相机扫描标签，我们为你读取配料。',
    'future.barcodeTitle': '条码扫描仪',
    'future.barcodeDesc': '即将上线 — 扫描条码即可获取完整成分分析。',
    'future.voiceTitle': '语音助手',
    'future.voiceDesc': '即将上线 — 直接语音询问任何配料问题。',
    'future.langTitle': '多语言支持',
    'future.langDesc': '即将上线 — 用你的首选语言阅读健康报告。',
    'future.notifyMe': '上线提醒我',
    'future.notified': '上线后我们会通知你',

    'ingredient.breadcrumbHome': '仪表板',
    'ingredient.backToDashboard': '返回仪表板',
    'ingredient.description': '简介',
    'ingredient.purpose': '在食品中的作用',
    'ingredient.healthEffects': '健康影响',
    'ingredient.countryRegulations': '各国监管情况',
    'ingredient.saferAlternatives': '更安全的替代品',
    'ingredient.researchSources': '研究来源',

    'analyzing.prefix': '正在分析',
    'analyzing.stage1': '正在解析配料',
    'analyzing.stage2': '正在比对全球法规',
    'analyzing.stage3': '正在生成健康报告',
    'analyzing.cancel': '取消',

    'table.ingredient': '配料',
    'table.reason': '原因',
    'table.risk': '风险',
    'table.caption': '配料风险明细',

    'chart.safe': '安全',
    'chart.moderate': '一般',
    'chart.highRisk': '高风险',
    'chart.unknown': '未知',
    'chart.aria': '风险分布图',

    'badge.safe': '安全',
    'badge.moderate': '中等风险',
    'badge.high': '高风险',
    'badge.unknown': '未知',

    'error.notFoundTitle': '页面未找到',
    'error.notFoundDesc': '你要找的页面不存在或已被移动。',
    'error.serverTitle': '我们这边出了点问题',
    'error.serverDesc': '我们团队已收到通知，请稍后再试。',
    'error.networkTitle': '请检查网络连接',
    'error.networkDesc': '无法连接到 NutriGuard AI，请重新连接后重试。',
    'error.noAnalysisTitle': '找不到该检测',
    'error.noAnalysisDesc': '该分析可能已被删除或链接不正确。',
    'error.noAnalysisAction': '开始新的分析',
  },

  ar: {
    'nav.home': 'الرئيسية',
    'nav.dashboard': 'لوحة المعلومات',
    'nav.history': 'سجل الفحص',
    'nav.compare': 'مقارنة المنتجات',
    'nav.future': 'أدوات مستقبلية',
    'nav.settings': 'الإعدادات',
    'nav.help': 'المساعدة والمصادر',
    'nav.logout': 'تسجيل الخروج',
    'nav.profile': 'الملف الشخصي',
    'nav.searchPlaceholder': 'البحث عن المكونات أو الفحوصات السابقة…',

    'home.title': 'تحليل منتج غذائي',
    'home.subtitle': 'الصق قائمة المكونات أو أضفها واحداً تلو الآخر.',
    'home.tabPaste': 'لصق النص',
    'home.tabManual': 'إدخال يدوي',
    'home.tabScan': 'مسح ضوئي',
    'home.tip': 'نصيحة: الصق قائمة المكونات كاملة كما هي مطبوعة على العبوة للحصول على أدق نتيجة.',
    'home.productNameLabel': 'اسم المنتج (اختياري)',
    'home.productNamePlaceholder': 'مثال: كعكة الشوكولاتة',
    'home.analyzeBtn': 'تحليل المكونات',
    'home.recentScans': 'الفحوصات الأخيرة',
    'home.addIngredient': 'إضافة مكون',

    'dashboard.rescan': 'إعادة الفحص',
    'dashboard.compare': 'مقارنة',
    'dashboard.safetyScore': 'درجة الأمان',
    'dashboard.aiSummary': 'ملخص الذكاء الاصطناعي الصحي',
    'dashboard.ingredientBreakdown': 'تفاصيل المكونات',
    'dashboard.riskAnalysis': 'تحليل المخاطر',
    'dashboard.countryRegulation': 'اللوائح التنظيمية الدولية',
    'dashboard.saferAlternatives': 'بدائل صحية أكثر أماناً',
    'dashboard.quickStats': 'إحصائيات سريعة',
    'dashboard.ingredientsCount': 'المكونات',
    'dashboard.flaggedCount': 'عناصر مقلقة',
    'dashboard.allergyWarning': 'تحذير الحساسية',

    'compare.title': 'مقارنة المنتجات',
    'compare.subtitle': 'قارن بين منتجين لمعرفة الخيار الأكثر أماناً وصحة.',
    'compare.productA': 'المنتج أ',
    'compare.productB': 'المنتج ب',
    'compare.chooseProduct': 'اختر منتجاً',
    'compare.changeProduct': 'تغيير المنتج',
    'compare.compareNow': 'قارن الآن',
    'compare.betterChoice': 'الخيار الأفضل',
    'compare.recommendation': 'التوصية',

    'profile.title': 'الملف الشخصي والإعدادات',
    'profile.account': 'الحساب',
    'profile.fitness': 'الجيم واللياقة البدنية',
    'profile.allergies': 'الحساسية الغذائية',
    'profile.appearance': 'المظهر',
    'profile.language': 'اللغة',
    'profile.notifications': 'الإشعارات',
    'profile.privacy': 'الخصوصية والبيانات',
    'profile.saveChanges': 'حفظ التغييرات',
    'profile.darkMode': 'الوضع الداكن',
    'profile.selectLanguage': 'اختر لغتك المفضلة',
    'profile.logoutConfirm': 'هل أنت متأكد من رغبتك في تسجيل الخروج؟',
    'profile.loggedOutMsg': 'تم تسجيل خروجك بنجاح.',

    'common.cancel': 'إلغاء',
    'common.retry': 'إعادة المحاولة',
    'common.goHome': 'العودة للرئيسية',
    'common.contactSupport': 'اتصل بالدعم',
    'common.compare': 'مقارنة',
    'common.delete': 'حذف',
    'common.changeProduct': 'تغيير المنتج',
    'common.chooseProduct': 'اختر منتجاً',
    'common.backToSetup': 'العودة لإعداد المقارنة',
    'common.safetyPoints': 'نقاط الأمان',

    'dashboard.scanned': 'تم الفحص',
    'dashboard.moreOptions': 'خيارات أخرى',
    'dashboard.needSecondOpinion': 'تحتاج رأياً ثانياً؟',
    'dashboard.viewHistory': 'عرض سجل الفحص الخاص بك',

    'history.title': 'سجل الفحص',
    'history.subtitleOne': 'فحص محفوظ — مخزن بشكل دائم.',
    'history.subtitleMany': 'فحوصات محفوظة — مخزنة بشكل دائم.',
    'history.searchPlaceholder': 'ابحث في الفحوصات…',
    'history.searchLabel': 'البحث في سجل الفحص',
    'history.clearAll': 'مسح كل السجل',
    'history.clearConfirm': 'هل أنت متأكد من رغبتك في مسح سجل الفحص بالكامل؟',
    'history.clearedToast': 'تم مسح سجل الفحص.',
    'history.removedPrefix': 'تمت إزالة',
    'history.removedSuffix': 'من سجل الفحص.',
    'history.emptyTitle': 'لا توجد فحوصات بعد',
    'history.emptyDesc': 'حلل منتجاً لبدء بناء سجل الفحص الدائم.',
    'history.emptyAction': 'حلل الآن',
    'history.noMatchStart': 'لا توجد فحوصات تطابق',
    'history.noMatchEnd': 'جرّب مسح البحث.',
    'history.gridView': 'عرض شبكي',
    'history.listView': 'عرض قائمة',
    'history.compareTitle': 'مقارنة المنتج',
    'history.deleteTitle': 'حذف الفحص',

    'compare.emptyTitle': 'اختر منتجين للمقارنة',
    'compare.emptyDesc': 'اختر من سجل الفحص أو حلل منتجاً جديداً للبدء.',
    'compare.emptyAction': 'الذهاب إلى سجل الفحص',
    'compare.noOtherProducts': 'لا توجد منتجات مفحوصة أخرى متاحة.',
    'compare.resultTitle': 'نتيجة المقارنة',
    'compare.backToSetup': 'العودة لإعداد المقارنة',
    'compare.safetyScore': 'درجة الأمان',
    'compare.riskLevel': 'مستوى الخطر',
    'compare.ingredientCount': 'عدد المكونات',
    'compare.harmfulCount': 'المكونات الضارة',
    'compare.customFallback': 'مخصص / مفحوص',
    'compare.saferChoiceIs': 'هو الخيار الأكثر أماناً — يتفوق بـ',
    'compare.pointsHigherSuffix': 'نقطة مع مكونات مقلقة أقل.',

    'future.ocrTitle': 'ماسح OCR',
    'future.ocrDesc': 'قريباً — امسح الملصق بالكاميرا وسنقرأ المكونات لك.',
    'future.barcodeTitle': 'ماسح الباركود',
    'future.barcodeDesc': 'قريباً — امسح الباركود للحصول على تحليل كامل فوري.',
    'future.voiceTitle': 'المساعد الصوتي',
    'future.voiceDesc': 'قريباً — اسأل NutriGuard AI بصوتك عن أي مكون.',
    'future.langTitle': 'دعم متعدد اللغات',
    'future.langDesc': 'قريباً — اقرأ تقاريرك الصحية بلغتك المفضلة.',
    'future.notifyMe': 'أعلمني',
    'future.notified': 'سنعلمك عند الإطلاق',

    'ingredient.breadcrumbHome': 'لوحة المعلومات',
    'ingredient.backToDashboard': 'العودة للوحة المعلومات',
    'ingredient.description': 'الوصف',
    'ingredient.purpose': 'دوره في الغذاء',
    'ingredient.healthEffects': 'الآثار الصحية',
    'ingredient.countryRegulations': 'اللوائح الدولية',
    'ingredient.saferAlternatives': 'بدائل أكثر أماناً',
    'ingredient.researchSources': 'المصادر البحثية',

    'analyzing.prefix': 'جارٍ تحليل',
    'analyzing.stage1': 'جارٍ قراءة المكونات',
    'analyzing.stage2': 'جارٍ مطابقة اللوائح العالمية',
    'analyzing.stage3': 'جارٍ إنشاء تقريرك الصحي',
    'analyzing.cancel': 'إلغاء',

    'table.ingredient': 'المكون',
    'table.reason': 'السبب',
    'table.risk': 'الخطر',
    'table.caption': 'تفاصيل مخاطر المكونات',

    'chart.safe': 'آمن',
    'chart.moderate': 'متوسط',
    'chart.highRisk': 'خطر مرتفع',
    'chart.unknown': 'غير معروف',
    'chart.aria': 'مخطط توزيع المخاطر',

    'badge.safe': 'آمن',
    'badge.moderate': 'خطر متوسط',
    'badge.high': 'خطر مرتفع',
    'badge.unknown': 'غير معروف',

    'error.notFoundTitle': 'الصفحة غير موجودة',
    'error.notFoundDesc': 'الصفحة التي تبحث عنها غير موجودة أو تم نقلها.',
    'error.serverTitle': 'حدث خطأ من جهتنا',
    'error.serverDesc': 'تم إشعار فريقنا. يرجى المحاولة مجدداً بعد قليل.',
    'error.networkTitle': 'تحقق من اتصالك بالإنترنت',
    'error.networkDesc': 'تعذر الوصول إلى NutriGuard AI. أعد الاتصال وحاول مجدداً.',
    'error.noAnalysisTitle': 'تعذر العثور على هذا الفحص',
    'error.noAnalysisDesc': 'قد يكون هذا التحليل محذوفاً أو الرابط غير صحيح.',
    'error.noAnalysisAction': 'بدء تحليل جديد',
  },

  ja: {
    'nav.home': 'ホーム',
    'nav.dashboard': 'ダッシュボード',
    'nav.history': 'スキャン履歴',
    'nav.compare': '製品比較',
    'nav.future': '今後のツール',
    'nav.settings': '設定',
    'nav.help': 'ヘルプと情報源',
    'nav.logout': 'ログアウト',
    'nav.profile': 'プロフィール',
    'nav.searchPlaceholder': '原材料や過去のスキャンを検索…',

    'home.title': '製品原材料を分析',
    'home.subtitle': '原材料リストを貼り付けるか、個別に追加してください。',
    'home.tabPaste': 'テキスト貼付',
    'home.tabManual': '手動入力',
    'home.tabScan': 'スキャン',
    'home.tip': 'ヒント：パッケージに記載された原材料をそのまま貼り付けると、最も正確な判定が得られます。',
    'home.productNameLabel': '製品名（任意）',
    'home.productNamePlaceholder': '例：チョコレートケーキ',
    'home.analyzeBtn': '原材料を分析する',
    'home.recentScans': '最近のスキャン',
    'home.addIngredient': '原材料を追加',

    'dashboard.rescan': '再スキャン',
    'dashboard.compare': '比較する',
    'dashboard.safetyScore': '安全性スコア',
    'dashboard.aiSummary': 'AI健康サマリー',
    'dashboard.ingredientBreakdown': '原材料の内訳',
    'dashboard.riskAnalysis': 'リスク分析',
    'dashboard.countryRegulation': '国別の規制状況',
    'dashboard.saferAlternatives': 'より安全な代替品',
    'dashboard.quickStats': '基本統計',
    'dashboard.ingredientsCount': '原材料数',
    'dashboard.flaggedCount': '要注意成分',
    'dashboard.allergyWarning': 'アレルギー警告',

    'compare.title': '製品を比較',
    'compare.subtitle': '2つの製品を比較して、より安全な選択肢を確認できます。',
    'compare.productA': '製品 A',
    'compare.productB': '製品 B',
    'compare.chooseProduct': '製品を選択',
    'compare.changeProduct': '製品を変更',
    'compare.compareNow': '今すぐ比較',
    'compare.betterChoice': 'おすすめの選択',
    'compare.recommendation': '推奨事項',

    'profile.title': 'プロフィールと設定',
    'profile.account': 'アカウント',
    'profile.fitness': 'ジム＆フィットネス',
    'profile.allergies': '食物アレルギー',
    'profile.appearance': '外観',
    'profile.language': '言語',
    'profile.notifications': '通知',
    'profile.privacy': 'プライバシーとデータ',
    'profile.saveChanges': '変更を保存',
    'profile.darkMode': 'ダークモード',
    'profile.selectLanguage': '使用する言語を選択',
    'profile.logoutConfirm': '本当にログアウトしますか？',
    'profile.loggedOutMsg': '正常にログアウトしました。',

    'common.cancel': 'キャンセル',
    'common.retry': '再試行',
    'common.goHome': 'ホームへ戻る',
    'common.contactSupport': 'サポートに連絡',
    'common.compare': '比較する',
    'common.delete': '削除',
    'common.changeProduct': '製品を変更',
    'common.chooseProduct': '製品を選択',
    'common.backToSetup': '比較設定に戻る',
    'common.safetyPoints': '安全性ポイント',

    'dashboard.scanned': 'スキャン日',
    'dashboard.moreOptions': 'その他のオプション',
    'dashboard.needSecondOpinion': 'セカンドオピニオンが必要ですか？',
    'dashboard.viewHistory': 'スキャン履歴を見る',

    'history.title': 'スキャン履歴',
    'history.subtitleOne': '件の保存済みスキャン — 永続的に保存されています。',
    'history.subtitleMany': '件の保存済みスキャン — 永続的に保存されています。',
    'history.searchPlaceholder': 'スキャンを検索…',
    'history.searchLabel': 'スキャン履歴を検索',
    'history.clearAll': '履歴をすべて削除',
    'history.clearConfirm': 'スキャン履歴をすべて削除してもよろしいですか？',
    'history.clearedToast': 'スキャン履歴を削除しました。',
    'history.removedPrefix': '削除しました',
    'history.removedSuffix': 'をスキャン履歴から。',
    'history.emptyTitle': 'まだスキャンがありません',
    'history.emptyDesc': '製品を分析して履歴を作り始めましょう。',
    'history.emptyAction': '今すぐ分析',
    'history.noMatchStart': '一致するスキャンはありません',
    'history.noMatchEnd': '検索条件をクリアしてみてください。',
    'history.gridView': 'グリッド表示',
    'history.listView': 'リスト表示',
    'history.compareTitle': '製品を比較',
    'history.deleteTitle': 'スキャンを削除',

    'compare.emptyTitle': '比較する2製品を選択',
    'compare.emptyDesc': '履歴から選ぶか、新しい製品を分析して始めましょう。',
    'compare.emptyAction': 'スキャン履歴へ',
    'compare.noOtherProducts': '他のスキャン済み製品はありません。',
    'compare.resultTitle': '比較結果',
    'compare.backToSetup': '比較設定に戻る',
    'compare.safetyScore': '安全性スコア',
    'compare.riskLevel': 'リスクレベル',
    'compare.ingredientCount': '原材料数',
    'compare.harmfulCount': '有害成分',
    'compare.customFallback': 'カスタム / スキャン済み',
    'compare.saferChoiceIs': 'がより安全な選択です —',
    'compare.pointsHigherSuffix': 'ポイント高く、要注意成分が少なくなっています。',

    'future.ocrTitle': 'OCRスキャナー',
    'future.ocrDesc': '近日公開 — カメラでラベルを撮影すると原材料を読み取ります。',
    'future.barcodeTitle': 'バーコードスキャナー',
    'future.barcodeDesc': '近日公開 — バーコードで全成分分析を即時表示します。',
    'future.voiceTitle': '音声アシスタント',
    'future.voiceDesc': '近日公開 — あらゆる原材料について音声で質問できます.',
    'future.langTitle': '多言語サポート',
    'future.langDesc': '近日公開 — お好みの言語で健康レポートを読めます。',
    'future.notifyMe': '通知を受け取る',
    'future.notified': '公開時にお知らせします',

    'ingredient.breadcrumbHome': 'ダッシュボード',
    'ingredient.backToDashboard': 'ダッシュボードに戻る',
    'ingredient.description': '概要',
    'ingredient.purpose': '食品における役割',
    'ingredient.healthEffects': '健康への影響',
    'ingredient.countryRegulations': '国別の規制状況',
    'ingredient.saferAlternatives': 'より安全な代替品',
    'ingredient.researchSources': '研究ソース',

    'analyzing.prefix': '分析中',
    'analyzing.stage1': '原材料を読み取り中',
    'analyzing.stage2': '世界の規制と照合中',
    'analyzing.stage3': '健康レポートを生成中',
    'analyzing.cancel': 'キャンセル',

    'table.ingredient': '原材料',
    'table.reason': '理由',
    'table.risk': 'リスク',
    'table.caption': '原材料リスク内訳',

    'chart.safe': '安全',
    'chart.moderate': '注意',
    'chart.highRisk': '高リスク',
    'chart.unknown': '不明',
    'chart.aria': 'リスク分布チャート',

    'badge.safe': '安全',
    'badge.moderate': '注意',
    'badge.high': '高リスク',
    'badge.unknown': '不明',

    'error.notFoundTitle': 'ページが見つかりません',
    'error.notFoundDesc': 'お探しのページは存在しないか、移動した可能性があります。',
    'error.serverTitle': 'サーバー側で問題が発生しました',
    'error.serverDesc': 'チームに通知済みです。しばらくしてから再試行してください。',
    'error.networkTitle': 'インターネット接続を確認してください',
    'error.networkDesc': 'NutriGuard AIに接続できませんでした。再接続して再試行してください。',
    'error.noAnalysisTitle': 'このスキャンが見つかりません',
    'error.noAnalysisDesc': 'この分析は削除されたか、リンクが正しくない可能性があります。',
    'error.noAnalysisAction': '新しい分析を開始',
  },

  pt: {
    'nav.home': 'Início',
    'nav.dashboard': 'Painel',
    'nav.history': 'Histórico de Verificações',
    'nav.compare': 'Comparar Produtos',
    'nav.future': 'Próximas Ferramentas',
    'nav.settings': 'Configurações',
    'nav.help': 'Ajuda & Fontes',
    'nav.logout': 'Sair',
    'nav.profile': 'Perfil',
    'nav.searchPlaceholder': 'Pesquisar ingredientes ou histórico…',

    'home.title': 'Analisar um produto',
    'home.subtitle': 'Cole a lista de ingredientes ou adicione um por um.',
    'home.tabPaste': 'Colar Texto',
    'home.tabManual': 'Criar Manualmente',
    'home.tabScan': 'Escanear',
    'home.tip': 'Dica: cole a lista de ingredientes completa exatamente como na embalagem para maior precisão.',
    'home.productNameLabel': 'Nome do produto (opcional)',
    'home.productNamePlaceholder': 'ex.: Bolo de Chocolate',
    'home.analyzeBtn': 'Analisar Ingredientes',
    'home.recentScans': 'Análises recentes',
    'home.addIngredient': 'Adicionar ingrediente',

    'dashboard.rescan': 'Reanalisar',
    'dashboard.compare': 'Comparar',
    'dashboard.safetyScore': 'Pontuação de Segurança',
    'dashboard.aiSummary': 'Resumo de Saúde IA',
    'dashboard.ingredientBreakdown': 'Detalhamento de Ingredientes',
    'dashboard.riskAnalysis': 'Análise de Risco',
    'dashboard.countryRegulation': 'Regulamentação por País',
    'dashboard.saferAlternatives': 'Alternativas Mais Seguras',
    'dashboard.quickStats': 'Estatísticas Rápidas',
    'dashboard.ingredientsCount': 'Ingredientes',
    'dashboard.flaggedCount': 'Marcados',
    'dashboard.allergyWarning': 'Aviso de Alergia',

    'compare.title': 'Comparar produtos',
    'compare.subtitle': 'Selecione dois produtos para ver qual é a opção mais saudável.',
    'compare.productA': 'Produto A',
    'compare.productB': 'Produto B',
    'compare.chooseProduct': 'Escolher produto',
    'compare.changeProduct': 'Mudar produto',
    'compare.compareNow': 'Comparar Agora',
    'compare.betterChoice': 'Melhor Escolha',
    'compare.recommendation': 'Recomendação',

    'profile.title': 'Perfil e Configurações',
    'profile.account': 'Conta',
    'profile.fitness': 'Academia e Fitness',
    'profile.allergies': 'Alergias Alimentares',
    'profile.appearance': 'Aparência',
    'profile.language': 'Idioma',
    'profile.notifications': 'Notificações',
    'profile.privacy': 'Privacidade e Dados',
    'profile.saveChanges': 'Salvar Alterações',
    'profile.darkMode': 'Modo escuro',
    'profile.selectLanguage': 'Selecione seu idioma preferido',
    'profile.logoutConfirm': 'Tem certeza que deseja sair?',
    'profile.loggedOutMsg': 'Você saiu com sucesso.',

    'common.cancel': 'Cancelar',
    'common.retry': 'Tentar novamente',
    'common.goHome': 'Ir para o início',
    'common.contactSupport': 'Falar com o suporte',
    'common.compare': 'Comparar',
    'common.delete': 'Excluir',
    'common.changeProduct': 'Mudar produto',
    'common.chooseProduct': 'Escolher produto',
    'common.backToSetup': 'Voltar à comparação',
    'common.safetyPoints': 'pontos de segurança',

    'dashboard.scanned': 'Analisado em',
    'dashboard.moreOptions': 'Mais opções',
    'dashboard.needSecondOpinion': 'Precisa de uma segunda opinião?',
    'dashboard.viewHistory': 'Ver seu histórico de verificações',

    'history.title': 'Histórico de Verificações',
    'history.subtitleOne': 'verificação salva — armazenada de forma persistente.',
    'history.subtitleMany': 'verificações salvas — armazenadas de forma persistente.',
    'history.searchPlaceholder': 'Pesquisar verificações…',
    'history.searchLabel': 'Pesquisar histórico',
    'history.clearAll': 'Limpar todo o histórico',
    'history.clearConfirm': 'Tem certeza que deseja limpar todo o histórico?',
    'history.clearedToast': 'Histórico apagado.',
    'history.removedPrefix': 'Removido',
    'history.removedSuffix': 'do histórico.',
    'history.emptyTitle': 'Nenhuma verificação ainda',
    'history.emptyDesc': 'Analise um produto para começar seu histórico.',
    'history.emptyAction': 'Analisar agora',
    'history.noMatchStart': 'Nenhuma verificação corresponde a',
    'history.noMatchEnd': 'Tente limpar sua pesquisa.',
    'history.gridView': 'Vista em grade',
    'history.listView': 'Vista em lista',
    'history.compareTitle': 'Comparar produto',
    'history.deleteTitle': 'Excluir verificação',

    'compare.emptyTitle': 'Escolha dois produtos para comparar',
    'compare.emptyDesc': 'Escolha do histórico ou analise um novo produto.',
    'compare.emptyAction': 'Ir para o histórico',
    'compare.noOtherProducts': 'Nenhum outro produto verificado disponível.',
    'compare.resultTitle': 'Resultado da comparação',
    'compare.backToSetup': 'Voltar à comparação',
    'compare.safetyScore': 'Pontuação de segurança',
    'compare.riskLevel': 'Nível de risco',
    'compare.ingredientCount': 'Qtd. de ingredientes',
    'compare.harmfulCount': 'Ingredientes nocivos',
    'compare.customFallback': 'Personalizado / Verificado',
    'compare.saferChoiceIs': 'é a escolha mais segura — com',
    'compare.pointsHigherSuffix': 'pontos a mais e menos ingredientes marcados.',

    'future.ocrTitle': 'Scanner OCR',
    'future.ocrDesc': 'Em breve — escaneie um rótulo com a câmera e leremos os ingredientes.',
    'future.barcodeTitle': 'Scanner de código de barras',
    'future.barcodeDesc': 'Em breve — escaneie um código de barras para ver a análise completa.',
    'future.voiceTitle': 'Assistente de voz',
    'future.voiceDesc': 'Em breve — pergunte em voz alta sobre qualquer ingrediente.',
    'future.langTitle': 'Suporte multilíngue',
    'future.langDesc': 'Em breve — leia seus relatórios no seu idioma preferido.',
    'future.notifyMe': 'Me avise',
    'future.notified': 'Avisaremos você',

    'ingredient.breadcrumbHome': 'Painel',
    'ingredient.backToDashboard': 'Voltar ao painel',
    'ingredient.description': 'Descrição',
    'ingredient.purpose': 'Função no alimento',
    'ingredient.healthEffects': 'Efeitos na saúde',
    'ingredient.countryRegulations': 'Regulamentação por país',
    'ingredient.saferAlternatives': 'Alternativas mais seguras',
    'ingredient.researchSources': 'Fontes científicas',

    'analyzing.prefix': 'Analisando',
    'analyzing.stage1': 'Lendo ingredientes',
    'analyzing.stage2': 'Consultando regulamentações globais',
    'analyzing.stage3': 'Gerando seu relatório de saúde',
    'analyzing.cancel': 'Cancelar',

    'table.ingredient': 'Ingrediente',
    'table.reason': 'Motivo',
    'table.risk': 'Risco',
    'table.caption': 'Detalhamento de risco por ingrediente',

    'chart.safe': 'Seguro',
    'chart.moderate': 'Moderado',
    'chart.highRisk': 'Alto risco',
    'chart.unknown': 'Desconhecido',
    'chart.aria': 'Gráfico de distribuição de risco',

    'badge.safe': 'Seguro',
    'badge.moderate': 'Risco moderado',
    'badge.high': 'Alto risco',
    'badge.unknown': 'Desconhecido',

    'error.notFoundTitle': 'Página não encontrada',
    'error.notFoundDesc': 'A página procurada não existe ou foi movida.',
    'error.serverTitle': 'Algo deu errado do nosso lado',
    'error.serverDesc': 'Nossa equipe foi notificada. Tente novamente em instantes.',
    'error.networkTitle': 'Verifique sua conexão',
    'error.networkDesc': 'Não conseguimos alcançar o NutriGuard AI. Reconecte e tente de novo.',
    'error.noAnalysisTitle': 'Não encontramos esta verificação',
    'error.noAnalysisDesc': 'Esta análise pode ter sido excluída ou o link está incorreto.',
    'error.noAnalysisAction': 'Iniciar nova análise',
  },

  ru: {
    'nav.home': 'Главная',
    'nav.dashboard': 'Панель',
    'nav.history': 'История проверок',
    'nav.compare': 'Сравнение продуктов',
    'nav.future': 'Новые инструменты',
    'nav.settings': 'Настройки',
    'nav.help': 'Помощь и источники',
    'nav.logout': 'Выйти',
    'nav.profile': 'Профиль',
    'nav.searchPlaceholder': 'Поиск по ингредиентам или проверкам…',

    'home.title': 'Анализ состава продукта',
    'home.subtitle': 'Вставьте список ингредиентов или добавьте их вручную.',
    'home.tabPaste': 'Вставить текст',
    'home.tabManual': 'Ввести вручную',
    'home.tabScan': 'Сканировать',
    'home.tip': 'Совет: скопируйте состав точно с упаковки для наиболее точного анализа.',
    'home.productNameLabel': 'Название продукта (необязательно)',
    'home.productNamePlaceholder': 'например, Шоколадный торт',
    'home.analyzeBtn': 'Анализировать состав',
    'home.recentScans': 'Недавние проверки',
    'home.addIngredient': 'Добавить ингредиент',

    'dashboard.rescan': 'Повторить анализ',
    'dashboard.compare': 'Сравнить',
    'dashboard.safetyScore': 'Оценка безопасности',
    'dashboard.aiSummary': 'ИИ-сводка о здоровье',
    'dashboard.ingredientBreakdown': 'Разбор ингредиентов',
    'dashboard.riskAnalysis': 'Анализ рисков',
    'dashboard.countryRegulation': 'Регулирование в странах',
    'dashboard.saferAlternatives': 'Безопасные альтернативы',
    'dashboard.quickStats': 'Статистика',
    'dashboard.ingredientsCount': 'Ингредиенты',
    'dashboard.flaggedCount': 'С рисками',
    'dashboard.allergyWarning': 'Предупреждение об аллергенах',

    'compare.title': 'Сравнение продуктов',
    'compare.subtitle': 'Сравните два продукта, чтобы выбрать наиболее безопасный.',
    'compare.productA': 'Продукт A',
    'compare.productB': 'Продукт B',
    'compare.chooseProduct': 'Выбрать продукт',
    'compare.changeProduct': 'Изменить продукт',
    'compare.compareNow': 'Сравнить сейчас',
    'compare.betterChoice': 'Лучший выбор',
    'compare.recommendation': 'Рекомендация',

    'profile.title': 'Профиль и настройки',
    'profile.account': 'Аккаунт',
    'profile.fitness': 'Фитнес и тренировки',
    'profile.allergies': 'Пищевая аллергия',
    'profile.appearance': 'Оформление',
    'profile.language': 'Язык',
    'profile.notifications': 'Уведомления',
    'profile.privacy': 'Конфиденциальность',
    'profile.saveChanges': 'Сохранить изменения',
    'profile.darkMode': 'Темная тема',
    'profile.selectLanguage': 'Выберите предпочтительный язык',
    'profile.logoutConfirm': 'Вы уверены, что хотите выйти?',
    'profile.loggedOutMsg': 'Вы успешно вышли из системы.',

    'common.cancel': 'Отмена',
    'common.retry': 'Повторить',
    'common.goHome': 'На главную',
    'common.contactSupport': 'Связаться с поддержкой',
    'common.compare': 'Сравнить',
    'common.delete': 'Удалить',
    'common.changeProduct': 'Изменить продукт',
    'common.chooseProduct': 'Выбрать продукт',
    'common.backToSetup': 'Назад к сравнению',
    'common.safetyPoints': 'баллов безопасности',

    'dashboard.scanned': 'Проверено',
    'dashboard.moreOptions': 'Другие опции',
    'dashboard.needSecondOpinion': 'Нужно второе мнение?',
    'dashboard.viewHistory': 'Посмотреть историю проверок',

    'history.title': 'История проверок',
    'history.subtitleOne': 'сохранённая проверка — хранится постоянно.',
    'history.subtitleMany': 'сохранённых проверок — хранятся постоянно.',
    'history.searchPlaceholder': 'Поиск проверок…',
    'history.searchLabel': 'Поиск по истории',
    'history.clearAll': 'Очистить всю историю',
    'history.clearConfirm': 'Вы уверены, что хотите очистить всю историю проверок?',
    'history.clearedToast': 'История проверок очищена.',
    'history.removedPrefix': 'Удалено',
    'history.removedSuffix': 'из истории проверок.',
    'history.emptyTitle': 'Проверок пока нет',
    'history.emptyDesc': 'Проанализируйте продукт, чтобы начать историю.',
    'history.emptyAction': 'Анализировать сейчас',
    'history.noMatchStart': 'Ничего не найдено по запросу',
    'history.noMatchEnd': 'Попробуйте очистить поиск.',
    'history.gridView': 'Вид сеткой',
    'history.listView': 'Вид списком',
    'history.compareTitle': 'Сравнить продукт',
    'history.deleteTitle': 'Удалить проверку',

    'compare.emptyTitle': 'Выберите два продукта для сравнения',
    'compare.emptyDesc': 'Выберите из истории или проанализируйте новый продукт.',
    'compare.emptyAction': 'Перейти к истории',
    'compare.noOtherProducts': 'Других проверенных продуктов нет.',
    'compare.resultTitle': 'Результат сравнения',
    'compare.backToSetup': 'Назад к сравнению',
    'compare.safetyScore': 'Оценка безопасности',
    'compare.riskLevel': 'Уровень риска',
    'compare.ingredientCount': 'Число ингредиентов',
    'compare.harmfulCount': 'Вредные ингредиенты',
    'compare.customFallback': 'Свой / Проверенный',
    'compare.saferChoiceIs': '— более безопасный выбор, набирает на',
    'compare.pointsHigherSuffix': 'баллов больше с меньшим числом рисков.',

    'future.ocrTitle': 'OCR-сканер',
    'future.ocrDesc': 'Скоро — наведите камеру на этикетку, и мы прочитаем состав.',
    'future.barcodeTitle': 'Сканер штрих-кодов',
    'future.barcodeDesc': 'Скоро — сканируйте штрих-код для полного анализа.',
    'future.voiceTitle': 'Голосовой помощник',
    'future.voiceDesc': 'Скоро — спрашивайте вслух о любом ингредиенте.',
    'future.langTitle': 'Мультиязычность',
    'future.langDesc': 'Скоро — читайте отчёты на предпочитаемом языке.',
    'future.notifyMe': 'Уведомить меня',
    'future.notified': 'Мы вас уведомим',

    'ingredient.breadcrumbHome': 'Панель',
    'ingredient.backToDashboard': 'Назад к панели',
    'ingredient.description': 'Описание',
    'ingredient.purpose': 'Роль в продукте',
    'ingredient.healthEffects': 'Влияние на здоровье',
    'ingredient.countryRegulations': 'Регулирование в странах',
    'ingredient.saferAlternatives': 'Безопасные альтернативы',
    'ingredient.researchSources': 'Научные источники',

    'analyzing.prefix': 'Анализ',
    'analyzing.stage1': 'Чтение ингредиентов',
    'analyzing.stage2': 'Сверка с мировыми нормами',
    'analyzing.stage3': 'Создание отчёта о здоровье',
    'analyzing.cancel': 'Отмена',

    'table.ingredient': 'Ингредиент',
    'table.reason': 'Причина',
    'table.risk': 'Риск',
    'table.caption': 'Разбор рисков по ингредиентам',

    'chart.safe': 'Безопасно',
    'chart.moderate': 'Умеренно',
    'chart.highRisk': 'Высокий риск',
    'chart.unknown': 'Неизвестно',
    'chart.aria': 'Диаграмма распределения рисков',

    'badge.safe': 'Безопасно',
    'badge.moderate': 'Умеренный риск',
    'badge.high': 'Высокий риск',
    'badge.unknown': 'Неизвестно',

    'error.notFoundTitle': 'Страница не найдена',
    'error.notFoundDesc': 'Искомая страница не существует или была перемещена.',
    'error.serverTitle': 'Что-то пошло не так на нашей стороне',
    'error.serverDesc': 'Наша команда уведомлена. Попробуйте ещё раз чуть позже.',
    'error.networkTitle': 'Проверьте подключение к интернету',
    'error.networkDesc': 'Не удалось связаться с NutriGuard AI. Переподключитесь.',
    'error.noAnalysisTitle': 'Эта проверка не найдена',
    'error.noAnalysisDesc': 'Этот анализ мог быть удалён или ссылка неверна.',
    'error.noAnalysisAction': 'Начать новый анализ',
  },

  it: {
    'nav.home': 'Home',
    'nav.dashboard': 'Dashboard',
    'nav.history': 'Cronologia Scansioni',
    'nav.compare': 'Confronta Prodotti',
    'nav.future': 'Strumenti Futuri',
    'nav.settings': 'Impostazioni',
    'nav.help': 'Aiuto & Fonti',
    'nav.logout': 'Disconnetti',
    'nav.profile': 'Profilo',
    'nav.searchPlaceholder': 'Cerca ingredienti o scansioni…',

    'home.title': 'Analizza un prodotto',
    'home.subtitle': 'Incolla la lista degli ingredienti o aggiungili uno alla volta.',
    'home.tabPaste': 'Incolla Testo',
    'home.tabManual': 'Inserimento Manuale',
    'home.tabScan': 'Scansiona',
    'home.tip': 'Suggerimento: incolla la lista completa esattamente come sulla confezione per la massima precisione.',
    'home.productNameLabel': 'Nome prodotto (facoltativo)',
    'home.productNamePlaceholder': 'es. Torta al Cioccolato',
    'home.analyzeBtn': 'Analizza Ingredienti',
    'home.recentScans': 'Scansioni recenti',
    'home.addIngredient': 'Aggiungi ingrediente',

    'dashboard.rescan': 'Nuova scansione',
    'dashboard.compare': 'Confronta',
    'dashboard.safetyScore': 'Punteggio di Sicurezza',
    'dashboard.aiSummary': 'Riepilogo Salute IA',
    'dashboard.ingredientBreakdown': 'Dettaglio Ingredienti',
    'dashboard.riskAnalysis': 'Analisi dei Rischi',
    'dashboard.countryRegulation': 'Normative per Paese',
    'dashboard.saferAlternatives': 'Alternative Più Sicure',
    'dashboard.quickStats': 'Statistiche Rapide',
    'dashboard.ingredientsCount': 'Ingredienti',
    'dashboard.flaggedCount': 'Segnalati',
    'dashboard.allergyWarning': 'Avviso Allergeni',

    'compare.title': 'Confronta prodotti',
    'compare.subtitle': 'Seleziona due prodotti per scoprire la scelta più salutare.',
    'compare.productA': 'Prodotto A',
    'compare.productB': 'Prodotto B',
    'compare.chooseProduct': 'Scegli un prodotto',
    'compare.changeProduct': 'Cambia prodotto',
    'compare.compareNow': 'Confronta Ora',
    'compare.betterChoice': 'Scelta Migliore',
    'compare.recommendation': 'Raccomandazione',

    'profile.title': 'Profilo & Impostazioni',
    'profile.account': 'Account',
    'profile.fitness': 'Palestra e Fitness',
    'profile.allergies': 'Allergie Alimentari',
    'profile.appearance': 'Aspetto',
    'profile.language': 'Lingua',
    'profile.notifications': 'Notifiche',
    'profile.privacy': 'Privacy & Dati',
    'profile.saveChanges': 'Salva Modifiche',
    'profile.darkMode': 'Modalità scura',
    'profile.selectLanguage': 'Seleziona la tua lingua preferita',
    'profile.logoutConfirm': 'Sei sicuro di voler uscire?',
    'profile.loggedOutMsg': 'Disconnessione avvenuta con successo.',

    'common.cancel': 'Annulla',
    'common.retry': 'Riprova',
    'common.goHome': 'Torna alla Home',
    'common.contactSupport': 'Contatta il supporto',
    'common.compare': 'Confronta',
    'common.delete': 'Elimina',
    'common.changeProduct': 'Cambia prodotto',
    'common.chooseProduct': 'Scegli un prodotto',
    'common.backToSetup': 'Torna al confronto',
    'common.safetyPoints': 'punti sicurezza',

    'dashboard.scanned': 'Analizzato il',
    'dashboard.moreOptions': 'Altre opzioni',
    'dashboard.needSecondOpinion': 'Vuoi un secondo parere?',
    'dashboard.viewHistory': 'Vedi la tua cronologia scansioni',

    'history.title': 'Cronologia Scansioni',
    'history.subtitleOne': 'scansione salvata — archiviata in modo persistente.',
    'history.subtitleMany': 'scansioni salvate — archiviate in modo persistente.',
    'history.searchPlaceholder': 'Cerca scansioni…',
    'history.searchLabel': 'Cerca nella cronologia',
    'history.clearAll': 'Cancella tutta la cronologia',
    'history.clearConfirm': 'Sei sicuro di voler cancellare l’intera cronologia?',
    'history.clearedToast': 'Cronologia cancellata.',
    'history.removedPrefix': 'Rimosso',
    'history.removedSuffix': 'dalla cronologia.',
    'history.emptyTitle': 'Nessuna scansione ancora',
    'history.emptyDesc': 'Analizza un prodotto per iniziare la tua cronologia.',
    'history.emptyAction': 'Analizza ora',
    'history.noMatchStart': 'Nessuna scansione corrisponde a',
    'history.noMatchEnd': 'Prova a cancellare la ricerca.',
    'history.gridView': 'Vista griglia',
    'history.listView': 'Vista elenco',
    'history.compareTitle': 'Confronta prodotto',
    'history.deleteTitle': 'Elimina scansione',

    'compare.emptyTitle': 'Scegli due prodotti da confrontare',
    'compare.emptyDesc': 'Scegli dalla cronologia o analizza un nuovo prodotto.',
    'compare.emptyAction': 'Vai alla cronologia',
    'compare.noOtherProducts': 'Nessun altro prodotto scansionato disponibile.',
    'compare.resultTitle': 'Risultato del confronto',
    'compare.backToSetup': 'Torna al confronto',
    'compare.safetyScore': 'Punteggio di sicurezza',
    'compare.riskLevel': 'Livello di rischio',
    'compare.ingredientCount': 'Numero ingredienti',
    'compare.harmfulCount': 'Ingredienti nocivi',
    'compare.customFallback': 'Personalizzato / Scansionato',
    'compare.saferChoiceIs': 'è la scelta più sicura — con',
    'compare.pointsHigherSuffix': 'punti in più e meno ingredienti segnalati.',

    'future.ocrTitle': 'Scanner OCR',
    'future.ocrDesc': 'Prossimamente — inquadra un’etichetta e leggeremo gli ingredienti.',
    'future.barcodeTitle': 'Scanner codici a barre',
    'future.barcodeDesc': 'Prossimamente — scansiona un barcode per l’analisi completa.',
    'future.voiceTitle': 'Assistente vocale',
    'future.voiceDesc': 'Prossimamente — chiedi a voce di qualsiasi ingrediente.',
    'future.langTitle': 'Supporto multilingua',
    'future.langDesc': 'Prossimamente — leggi i report nella tua lingua preferita.',
    'future.notifyMe': 'Avvisami',
    'future.notified': 'Ti avviseremo',

    'ingredient.breadcrumbHome': 'Dashboard',
    'ingredient.backToDashboard': 'Torna alla Dashboard',
    'ingredient.description': 'Descrizione',
    'ingredient.purpose': 'Funzione nell’alimento',
    'ingredient.healthEffects': 'Effetti sulla salute',
    'ingredient.countryRegulations': 'Normative per Paese',
    'ingredient.saferAlternatives': 'Alternative più sicure',
    'ingredient.researchSources': 'Fonti scientifiche',

    'analyzing.prefix': 'Analisi di',
    'analyzing.stage1': 'Lettura ingredienti',
    'analyzing.stage2': 'Controllo normative globali',
    'analyzing.stage3': 'Generazione report salute',
    'analyzing.cancel': 'Annulla',

    'table.ingredient': 'Ingrediente',
    'table.reason': 'Motivo',
    'table.risk': 'Rischio',
    'table.caption': 'Dettaglio rischi per ingrediente',

    'chart.safe': 'Sicuro',
    'chart.moderate': 'Moderato',
    'chart.highRisk': 'Rischio alto',
    'chart.unknown': 'Sconosciuto',
    'chart.aria': 'Grafico distribuzione rischi',

    'badge.safe': 'Sicuro',
    'badge.moderate': 'Rischio moderato',
    'badge.high': 'Rischio alto',
    'badge.unknown': 'Sconosciuto',

    'error.notFoundTitle': 'Pagina non trovata',
    'error.notFoundDesc': 'La pagina cercata non esiste o è stata spostata.',
    'error.serverTitle': 'Qualcosa è andato storto',
    'error.serverDesc': 'Il nostro team è stato avvisato. Riprova tra un momento.',
    'error.networkTitle': 'Controlla la connessione internet',
    'error.networkDesc': 'Non riusciamo a raggiungere NutriGuard AI. Riconnettiti e riprova.',
    'error.noAnalysisTitle': 'Scansione non trovata',
    'error.noAnalysisDesc': 'Questa analisi potrebbe essere stata eliminata o il link è errato.',
    'error.noAnalysisAction': 'Avvia una nuova analisi',
  },

  bn: {
    'nav.home': 'হোম',
    'nav.dashboard': 'ড্যাশবোর্ড',
    'nav.history': 'স্ক্যান ইতিহাস',
    'nav.compare': 'পণ্য তুলনা',
    'nav.future': 'ভবিষ্যত টুলস',
    'nav.settings': 'সেটিংস',
    'nav.help': 'সাহায্য ও তথ্যসূত্র',
    'nav.logout': 'লগ আউট',
    'nav.profile': 'প্রোফাইল',
    'nav.searchPlaceholder': 'উপাদান বা পূর্ববর্তী স্ক্যান খুঁজুন…',

    'home.title': 'পণ্য বিশ্লেষণ করুন',
    'home.subtitle': 'উপাদানের তালিকা পেস্ট করুন বা একে একে যোগ করুন।',
    'home.tabPaste': 'টেক্সট পেস্ট করুন',
    'home.tabManual': 'ম্যানুয়াল তৈরি করুন',
    'home.tabScan': 'স্ক্যান',
    'home.tip': 'টিপ: সবচেয়ে নির্ভুল ফলাফলের জন্য প্যাকেটের সম্পূর্ণ উপাদানের তালিকা পেস্ট করুন।',
    'home.productNameLabel': 'পণ্যের নাম (ঐচ্ছিক)',
    'home.productNamePlaceholder': 'যেমন: চকলেট কেক বা ম্যাগি',
    'home.analyzeBtn': 'উপাদান বিশ্লেষণ করুন',
    'home.recentScans': 'সাম্প্রতিক স্ক্যান',
    'home.addIngredient': 'উপাদান যোগ করুন',

    'dashboard.rescan': 'পুনরায় স্ক্যান',
    'dashboard.compare': 'তুলনা করুন',
    'dashboard.safetyScore': 'নিরাপত্তা স্কোর',
    'dashboard.aiSummary': 'এআই স্বাস্থ্য সারসংক্ষেপ',
    'dashboard.ingredientBreakdown': 'উপাদান বিবরণ',
    'dashboard.riskAnalysis': 'ঝুঁকি বিশ্লেষণ',
    'dashboard.countryRegulation': 'দেশীয় নিয়মাবলী',
    'dashboard.saferAlternatives': 'নিরাপদ বিকল্প',
    'dashboard.quickStats': 'দ্রুত পরিসংখ্যান',
    'dashboard.ingredientsCount': 'মোট উপাদান',
    'dashboard.flaggedCount': 'ঝুঁকিপূর্ণ উপাদান',
    'dashboard.allergyWarning': 'অ্যালার্জি সতর্কতা',

    'compare.title': 'পণ্য তুলনা করুন',
    'compare.subtitle': 'কোন পণ্যটি বেশি স্বাস্থ্যকর তা দেখতে দুটি পণ্য নির্বাচন করুন।',
    'compare.productA': 'পণ্য A',
    'compare.productB': 'পণ্য B',
    'compare.chooseProduct': 'পণ্য বেছে নিন',
    'compare.changeProduct': 'পণ্য পরিবর্তন করুন',
    'compare.compareNow': 'এখনই তুলনা করুন',
    'compare.betterChoice': 'উত্তম পছন্দ',
    'compare.recommendation': 'পরামর্শ',

    'profile.title': 'প্রোফাইল ও সেটিংস',
    'profile.account': 'অ্যাকাউন্ট',
    'profile.fitness': 'জিম ও ফিটনেস',
    'profile.allergies': 'খাদ্য অ্যালার্জি',
    'profile.appearance': 'চেহারা (Appearance)',
    'profile.language': 'ভাষা (Language)',
    'profile.notifications': 'বিজ্ঞপ্তি (Notifications)',
    'profile.privacy': 'গোপনীয়তা ও ডেটা',
    'profile.saveChanges': 'পরিবর্তন সংরক্ষণ করুন',
    'profile.darkMode': 'ডার্ক মোড',
    'profile.selectLanguage': 'আপনার পছন্দের ভাষা নির্বাচন করুন',
    'profile.logoutConfirm': 'আপনি কি নিশ্চিত যে লগ আউট করতে চান?',
    'profile.loggedOutMsg': 'আপনি সফলভাবে লগ আউট হয়েছেন।',

    'common.cancel': 'বাতিল করুন',
    'common.retry': 'পুনরায় চেষ্টা করুন',
    'common.goHome': 'হোমে যান',
    'common.contactSupport': 'সাপোর্টে যোগাযোগ করুন',
    'common.compare': 'তুলনা করুন',
    'common.delete': 'মুছুন',
    'common.changeProduct': 'পণ্য পরিবর্তন করুন',
    'common.chooseProduct': 'পণ্য বেছে নিন',
    'common.backToSetup': 'তুলনা সেটআপে ফিরে যান',
    'common.safetyPoints': 'নিরাপত্তা পয়েন্ট',

    'dashboard.scanned': 'স্ক্যান করা হয়েছে',
    'dashboard.moreOptions': 'আরও বিকল্প',
    'dashboard.needSecondOpinion': 'দ্বিতীয় মতামত চান?',
    'dashboard.viewHistory': 'আপনার স্ক্যান ইতিহাস দেখুন',

    'history.title': 'স্ক্যান ইতিহাস (History)',
    'history.subtitleOne': 'টি সংরক্ষিত স্ক্যান — স্থায়ীভাবে সংরক্ষিত।',
    'history.subtitleMany': 'টি সংরক্ষিত স্ক্যান — স্থায়ীভাবে সংরক্ষিত।',
    'history.searchPlaceholder': 'স্ক্যান খুঁজুন…',
    'history.searchLabel': 'স্ক্যান ইতিহাস খুঁজুন',
    'history.clearAll': 'সম্পূর্ণ ইতিহাস মুছুন',
    'history.clearConfirm': 'আপনি কি নিশ্চিত যে সম্পূর্ণ স্ক্যান ইতিহাস মুছতে চান?',
    'history.clearedToast': 'স্ক্যান ইতিহাস মুছে ফেলা হয়েছে।',
    'history.removedPrefix': 'সরানো হয়েছে',
    'history.removedSuffix': 'স্ক্যান ইতিহাস থেকে।',
    'history.emptyTitle': 'এখনও কোনো স্ক্যান নেই',
    'history.emptyDesc': 'আপনার স্থায়ী ইতিহাস তৈরি করতে একটি পণ্য বিশ্লেষণ করুন।',
    'history.emptyAction': 'এখনই বিশ্লেষণ করুন',
    'history.noMatchStart': 'কোনো স্ক্যান মেলেনি',
    'history.noMatchEnd': 'আপনার সার্চ মুছে দেখুন।',
    'history.gridView': 'গ্রিড ভিউ',
    'history.listView': 'তালিকা ভিউ',
    'history.compareTitle': 'পণ্য তুলনা করুন',
    'history.deleteTitle': 'স্ক্যান মুছুন',

    'compare.emptyTitle': 'তুলনার জন্য দুটি পণ্য বেছে নিন',
    'compare.emptyDesc': 'আপনার ইতিহাস থেকে বেছে নিন বা নতুন পণ্য বিশ্লেষণ করুন।',
    'compare.emptyAction': 'স্ক্যান ইতিহাসে যান',
    'compare.noOtherProducts': 'অন্য কোনো স্ক্যান করা পণ্য উপলব্ধ নেই।',
    'compare.resultTitle': 'তুলনার ফলাফল',
    'compare.backToSetup': 'তুলনা সেটআপে ফিরে যান',
    'compare.safetyScore': 'নিরাপত্তা স্কোর (Safety Score)',
    'compare.riskLevel': 'ঝুঁকির মাত্রা',
    'compare.ingredientCount': 'উপাদানের সংখ্যা',
    'compare.harmfulCount': 'ক্ষতিকর উপাদান',
    'compare.customFallback': 'কাস্টম / স্ক্যান করা',
    'compare.saferChoiceIs': 'অপেক্ষাকৃত নিরাপদ পছন্দ — এগিয়ে',
    'compare.pointsHigherSuffix': 'পয়েন্টে, কম ঝুঁকিপূর্ণ উপাদানসহ।',

    'future.ocrTitle': 'OCR স্ক্যানার',
    'future.ocrDesc': 'শীঘ্রই আসছে — ক্যামেরা দিয়ে লেবেল স্ক্যান করুন, আমরা উপাদান পড়ে দেব।',
    'future.barcodeTitle': 'বারকোড স্ক্যানার',
    'future.barcodeDesc': 'শীঘ্রই আসছে — সম্পূর্ণ বিশ্লেষণের জন্য বারকোড স্ক্যান করুন।',
    'future.voiceTitle': 'ভয়েস অ্যাসিস্ট্যান্ট',
    'future.voiceDesc': 'শীঘ্রই আসছে — যেকোনো উপাদান সম্পর্কে মুখে জিজ্ঞাসা করুন।',
    'future.langTitle': 'বহুভাষিক সমর্থন',
    'future.langDesc': 'শীঘ্রই আসছে — আপনার পছন্দের ভাষায় স্বাস্থ্য রিপোর্ট পড়ুন।',
    'future.notifyMe': 'আমাকে জানান',
    'future.notified': 'আমরা আপনাকে জানাব',

    'ingredient.breadcrumbHome': 'ড্যাশবোর্ড (Dashboard)',
    'ingredient.backToDashboard': 'ড্যাশবোর্ডে ফিরে যান',
    'ingredient.description': 'বিবরণ',
    'ingredient.purpose': 'খাদ্যে ভূমিকা',
    'ingredient.healthEffects': 'স্বাস্থ্যগত প্রভাব',
    'ingredient.countryRegulations': 'দেশীয় নিয়মাবলী',
    'ingredient.saferAlternatives': 'নিরাপদ বিকল্প',
    'ingredient.researchSources': 'গবেষণা সূত্র',

    'analyzing.prefix': 'বিশ্লেষণ চলছে',
    'analyzing.stage1': 'উপাদান পড়া হচ্ছে',
    'analyzing.stage2': 'বৈশ্বিক নিয়মের সাথে মিলানো হচ্ছে',
    'analyzing.stage3': 'আপনার স্বাস্থ্য রিপোর্ট তৈরি হচ্ছে',
    'analyzing.cancel': 'বাতিল করুন',

    'table.ingredient': 'উপাদান',
    'table.reason': 'কারণ',
    'table.risk': 'ঝুঁকি',
    'table.caption': 'উপাদান ঝুঁকি বিবরণ',

    'chart.safe': 'নিরাপদ',
    'chart.moderate': 'মাঝারি',
    'chart.highRisk': 'উচ্চ ঝুঁকি',
    'chart.unknown': 'অজানা',
    'chart.aria': 'ঝুঁকি বিতরণ চার্ট',

    'badge.safe': 'নিরাপদ',
    'badge.moderate': 'মাঝারি ঝুঁকি',
    'badge.high': 'উচ্চ ঝুঁকি',
    'badge.unknown': 'অজানা',

    'error.notFoundTitle': 'পেজ পাওয়া যায়নি',
    'error.notFoundDesc': 'আপনি যে পেজটি খুঁজছেন তা নেই বা সরানো হয়েছে।',
    'error.serverTitle': 'আমাদের দিকে সমস্যা হয়েছে',
    'error.serverDesc': 'আমাদের টিমকে জানানো হয়েছে। কিছুক্ষণ পরে আবার চেষ্টা করুন।',
    'error.networkTitle': 'ইন্টারনেট সংযোগ পরীক্ষা করুন',
    'error.networkDesc': 'NutriGuard AI-এর সাথে সংযোগ করা যায়নি। পুনরায় সংযোগ করে চেষ্টা করুন।',
    'error.noAnalysisTitle': 'এই স্ক্যান পাওয়া যায়নি',
    'error.noAnalysisDesc': 'এই বিশ্লেষণ মুছে ফেলা হয়ে থাকতে পারে বা লिंकটি ভুল।',
    'error.noAnalysisAction': 'নতুন বিশ্লেষণ শুরু করুন',
  },
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key) => key,
  languages: SUPPORTED_LANGUAGES,
})

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<SupportedLanguage>(() => {
    try {
      const saved = localStorage.getItem('nutriguard_language') as SupportedLanguage
      if (saved && SUPPORTED_LANGUAGES.some((l) => l.code === saved)) {
        return saved
      }
    } catch {
      // ignore
    }
    return 'en'
  })

  const setLanguage = (lang: SupportedLanguage) => {
    setLanguageState(lang)
    try {
      localStorage.setItem('nutriguard_language', lang)
    } catch {
      // ignore
    }
  }

  useEffect(() => {
    try {
      document.documentElement.lang = language
      document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr'
    } catch {
      // ignore (non-DOM environment)
    }
  }, [language])

  const t = (key: string): string => {
    const langDict = translations[language] || translations.en
    return langDict[key] || translations.en[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languages: SUPPORTED_LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)
